import streamlit as st

# -----------------------
# Hard-coded Items
# -----------------------
ITEMS = {
    #                                                                                                   WEAPONS
#ak-47
    "Wh": "AK-47 | Case Hardened (Blue Gem)",
    "Wi": "AK-47 | Case Hardened (Gold Gem)",
    "Zu": "AK-47 | Gold Arabesque",
    "a8": "AK-47 | Ice Coaled",
    "Sw": "AK-47 | Jungle Spray",
    "Y4": "AK-47 | Leet Museo",
    "S1": "AK-47 | Legion of Anubis",
    "aq": "AK-47 | Nightwish",
    "UU": "AK-47 | Panthera onca",
    "Xl": "AK-47 | Slate",
    "UW": "AK-47 | X-Ray",
    "C3": "AK-47 | Aquamarine Revenge",
    "dn": "AK-47 | Olyve Polycam",
    "dI": "AK-47 | B the Monster",
    "dB": "AK-47 | Crossfade",
    "co": "AK-47 | The Outsiders",
    "Ni": "AK-47 | Asiimov",
    "AV": "AK-47 | Black Laminate",
    "As": "AK-47 | Bloodsport",
    "FD": "AK-47 | Blue Laminate",
    "F8": "AK-47 | Case Hardened",
    "DW": "AK-47 | Elite Build",
    "FU": "AK-47 | Fire Serpent",
    "Co": "AK-47 | Frontside Misty",
    "CF": "AK-47 | Fuel Injector",
    "bN": "AK-47 | Head Shot",
    "AF": "AK-47 | Hydroponic",
    "Et": "AK-47 | Jaguar",
    "AG": "AK-47 | Jet Set",
    "BQ": "AK-47 | Neon Revolution",
    "Me": "AK-47 | Neon Rider",
    "Ag": "AK-47 | Orbit Mk01",
    "Qb": "AK-47 | Phantom Disruptor",
    "CX": "AK-47 | Point Disarray",
    "PV": "AK-47 | Rat Rod",
    "FN": "AK-47 | Red Laminate",
    "EU": "AK-47 | Redline",
    "HI": "AK-47 | Safari Mesh",
    "Qr": "AK-47 | Safety Net",
    "b5": "AK-47 | Steel Delta",
    "Lf": "AK-47 | The Empress",
    "N8": "AK-47 | Uncharted",
    "EE": "AK-47 | Vulcan",
    "Dl": "AK-47 | Wasteland Rebel",
    "QX": "AK-47 | Wild Lotus",
    "Db": "AK-47 | Cartel",
    "cI": "AK-47 | Inheritance",
    "f7": "AK-47 | The Oligarch",
    "d5": "AK-47 | Midnight Laminate",
    "eZ": "AK-47 | Wintergreen",
    "ee": "AK-47 | VariCamo Grey",
    "ez": "AK-47 | Nouveau Rouge",
    "fV": "AK-47 | Searing Rage",
#aug
    "ad": "AUG | Flame Jormungandr",
    "ZG": "AUG | Plague",
    "c0": "AUG | Luxe Trim",
    "c4": "AUG | Lil\" Pig",
    "dN": "AUG | Eye of Zapems",
    "aO": "AUG | Akihabara Accept",
    "Mu": "AUG | Amber Slipstream",
    "PW": "AUG | Arctic Wolf",
    "Bn": "AUG | Aristocrat",
    "Ex": "AUG | Bengal Tiger",
    "ET": "AUG | Chameleon",
    "G8": "AUG | Colony",
    "O0": "AUG | Death by Puppy",
    "B0": "AUG | Fleet Flock",
    "AQ": "AUG | Hot Rod",
    "N1": "AUG | Momentum",
    "Gr": "AUG | Radiation Hazard",
    "Ch": "AUG | Ricochet",
    "cG": "AUG | Snake Pit",
    "L1": "AUG | Stymphalian",
    "BS": "AUG | Syd Mead",
    "Ql": "AUG | Tom Cat",
    "EJ": "AUG | Torque",
    "Lr": "AUG | Triqua",
    "GD": "AUG | Wings",
    "gM": "AUG | Trigger Discipline",
    "d3": "AUG | Steel Sentinel",
    "eq": "AUG | Commando Company",
#awp
    "a7": "AWP | Chromatic Aberration",
    "Zq": "AWP | Desert Hydra",
    "c2": "AWP | CMYX",
    "dK": "AWP | Crakow!",
    "Tr": "AWP | Exoskeleton",
    "UR": "AWP | Fade",
    "aH": "AWP | POP AWP",
    "UX": "AWP | Silk Tiger",
    "Qt": "AWP | Acheron",
    "ES": "AWP | Asiimov",
    "N3": "AWP | Atheris",
    "b4": "AWP | Black Nile",
    "FM": "AWP | BOOM",
    "Qj": "AWP | Capillary",
    "PQ": "AWP | Containment Breach",
    "Ev": "AWP | Corticera",
    "GG": "AWP | Dragon Lore",
    "bx": "AWP | Duality",
    "FB": "AWP | Electric Hive",
    "CH": "AWP | Elite Build",
    "Av": "AWP | Fever Dream",
    "FW": "AWP | Graphite",
    "QW": "AWP | Gungnir",
    "C2": "AWP | Hyper Beast",
    "F7": "AWP | Lightning Strike",
    "DY": "AWP | Man-o\"-war",
    "AB": "AWP | Medusa",
    "Lz": "AWP | Mortis",
    "Nh": "AWP | Neo-Noir",
    "Ac": "AWP | Oni Taiji",
    "Mj": "AWP | PAW",
    "Bm": "AWP | Phobos",
    "GW": "AWP | Pink DDPAT",
    "Ej": "AWP | Redline",
    "AX": "AWP | Sun in Leo",
    "Ph": "AWP | The Prince",
    "Ox": "AWP | Wildfire",
    "DQ": "AWP | Worm God",
    "cH": "AWP | Chrome Cannon",
    "gA": "AWP | Ice Coaled",
    "do": "AWP | LongDog",
    "eW": "AWP | Green Energy",
    "e3": "AWP | Arsenic Spill",
    "fS": "AWP | Printstream",
#cz auto
    "E5": "CZ75-Auto | Hexane",
    "Ba": "CZ75-Auto | Imprint",
    "DO": "CZ75-Auto | Pole Position",
    "BJ": "CZ75-Auto | Polymer",
    "B3": "CZ75-Auto | Red Astor",
    "D7": "CZ75-Auto | Tigris",
    "EM": "CZ75-Auto | Twist",
    "Aw": "CZ75-Auto | Xiangliu",
    "C6": "CZ75-Auto | Yellow Jacket",
    "Xt": "CZ75-Auto | Circaetus",
    "ak": "CZ75-Auto | Syndicate",
    "Ty": "CZ75-Auto | Vendetta",
    "GJ": "CZ75-Auto | Chalice",
    "Fq": "CZ75-Auto | Crimson Web",
    "Qp": "CZ75-Auto | Distressed",
    "Ml": "CZ75-Auto | Eco",
    "Ov": "CZ75-Auto | Emerald",
    "GY": "CZ75-Auto | Nitro",
    "Lk": "CZ75-Auto | Tacticat",
    "Fk": "CZ75-Auto | The Fuschia Is Now",
    "Fm": "CZ75-Auto | Tread Plate",
    "Fj": "CZ75-Auto | Victoria",
    "d2": "CZ75-Auto | Copper Fiber",
    "fL": "CZ75-Auto | Pink Pearl",
    "c7": "CZ75-Auto | Clalom",
#deagle
    "Zr": "Desert Eagle | Fennec Fox",
    "c1": "Desert Eagle | Heart Threaded",
    "c3": "Desert Eagle | Starcade",
    "cz": "Desert Eagle | Calligraffiti",
    "dX": "Desert Eagle | Tilted",
    "Y5": "Desert Eagle | Ocean Drive",
    "S0": "Desert Eagle | Printstream",
    "aK": "Desert Eagle | Sputnik",
    "Xm": "Desert Eagle | Trigger Discipline",
    "AM": "Desert Eagle | Blaze",
    "Qk": "Desert Eagle | Blue Ply",
    "DU": "Desert Eagle | Bronze Deco",
    "FA": "Desert Eagle | Cobalt Disruption",
    "Mf": "Desert Eagle | Code Red",
    "D1": "Desert Eagle | Conspiracy",
    "Ci": "Desert Eagle | Corinthian",
    "Ey": "Desert Eagle | Crimson Web",
    "BV": "Desert Eagle | Directive",
    "Qq": "Desert Eagle | Emerald Jormungandr",
    "FV": "Desert Eagle | Golden Koi",
    "GI": "Desert Eagle | Hand Cannon",
    "Fo": "Desert Eagle | Heirloom",
    "F9": "Desert Eagle | Hypnotic",
    "CI": "Desert Eagle | Kumicho Dragon",
    "N4": "Desert Eagle | Light Rail",
    "Nj": "Desert Eagle | Mecha Industries",
    "AY": "Desert Eagle | Midnight Storm",
    "Df": "Desert Eagle | Naga",
    "A2": "Desert Eagle | Oxide Blaze",
    "Or": "Desert Eagle | Sunset Storm",
    "Gb": "Desert Eagle | Urban DDPAT",
    "d7": "Desert Eagle | Mint Fan",
    "e1": "Desert Eagle | Mulberry",
    "fa": "Desert Eagle | Serpent Strike",
#dual barettas
    "Tu": "Dual Berettas | Dezastre",
    "at": "Dual Berettas | Melondrama",
    "ZJ": "Dual Berettas | Tread",
    "af": "Dual Berettas | Twin Turbo",
    "Pa": "Dual Berettas | Balance",
    "Fh": "Dual Berettas | Black Limba",
    "GU": "Dual Berettas | Briar",
    "CQ": "Dual Berettas | Cartel",
    "Af": "Dual Berettas | Cobra Strike",
    "Cv": "Dual Berettas | Dualing Dragons",
    "O9": "Dual Berettas | Elite 1.6",
    "bC": "Dual Berettas | Flora Carnivora",
    "El": "Dual Berettas | Marina",
    "Fs": "Dual Berettas | Panther",
    "BE": "Dual Berettas | Royal Consorts",
    "Ms": "Dual Berettas | Shred",
    "De": "Dual Berettas | Urban Shock",
    "B8": "Dual Berettas | Ventilators",
    "cW": "Dual Berettas | Hideout",
    "gF": "Dual Berettas | Angel Eyes",
    "eI": "Dual Berettas | Rose Nacre",
    "em": "Dual Berettas | Polished Malachite",
    "fK": "Dual Berettas | BorDeux",
    "dM": "Dual Berettas | Sweet Little Angels",
    "ct": "Dual Berettas | Hydro Strike",
#famas
    "aj": "FAMAS | Meltdown",
    "dm": "FAMAS | Half Sleeve",
    "dH": "FAMAS | Halftone Wash",
    "as": "FAMAS | Rapid Eye Movement",
    "ZA": "FAMAS | ZX Spectron",
    "FC": "FAMAS | Afterimage",
    "Oy": "FAMAS | Commemoration",
    "OD": "FAMAS | Crypsis",
    "O8": "FAMAS | Decommissioned",
    "DK": "FAMAS | Djinn",
    "FS": "FAMAS | Doomkitty",
    "Mi": "FAMAS | Eye of Athena",
    "F4": "FAMAS | Hexane",
    "Ao": "FAMAS | Macabre",
    "BB": "FAMAS | Mecha Industries",
    "bI": "FAMAS | Meow 36",
    "DB": "FAMAS | Neural Net",
    "Ek": "FAMAS | Pulse",
    "BR": "FAMAS | Roll Cage",
    "EZ": "FAMAS | Sergeant",
    "Gl": "FAMAS | Styx",
    "Cw": "FAMAS | Survivor Z",
    "CK": "FAMAS | Valence",
    "bz": "FAMAS | Waters of Nephtys",
    "dx": "FAMAS | 2A2F",
    "d9": "FAMAS | Yeti Camo",
    "ex": "FAMAS | Palm",
    "fB": "FAMAS | Grey Ghost",
    "fR": "FAMAS | Bad Trip",
#five seven
    "ZC": "Five-SeveN | Boost Protocol",
    "Tq": "Five-SeveN | Fairy Tale",
    "a1": "Five-SeveN | Scrawl",
    "dW": "Five-SeveN | Midnight Paintover",
    "dd": "Five-SeveN | Heat Treated",
    "Nz": "Five-SeveN | Angry Mob",
    "O6": "Five-SeveN | Buddy",
    "Aa": "Five-SeveN | Candy Apple",
    "A3": "Five-SeveN | Capillary",
    "F0": "Five-SeveN | Case Hardened",
    "G7": "Five-SeveN | Contractor",
    "Fp": "Five-SeveN | Cooper Galaxy",
    "L9": "Five-SeveN | Flame Test",
    "D2": "Five-SeveN | Fowl Play",
    "Gv": "Five-SeveN | Hot Shot",
    "Ab": "Five-SeveN | Hyper Beast",
    "Ep": "Five-SeveN | Kami",
    "DM": "Five-SeveN | Monkey Business",
    "FK": "Five-SeveN | Nightshade",
    "HJ": "Five-SeveN | Orange Peel",
    "Cc": "Five-SeveN | Retrobution",
    "Bb": "Five-SeveN | Scumbria",
    "CL": "Five-SeveN | Triumvirate",
    "Du": "Five-SeveN | Urban Hazard",
    "Br": "Five-SeveN | Violent Daimyo",
    "cO": "Five-SeveN | Hybrid",
    "eG": "Five-SeveN | Sky Blue",
    "fH": "Five-SeveN | Autumn Thicket",
#g3sg1
    "T1": "G3SG1 | Digital Mesh",
    "aw": "G3SG1 | Dream Glade",
    "ZK": "G3SG1 | Keeping Tabs",
    "FI": "G3SG1 | Azure Zebra",
    "Pd": "G3SG1 | Black Sand",
    "AJ": "G3SG1 | Chronos",
    "Fd": "G3SG1 | Demeter",
    "HM": "G3SG1 | Desert Storm",
    "Cp": "G3SG1 | Flux",
    "Mn": "G3SG1 | High Seas",
    "Lq": "G3SG1 | Hunter",
    "Dv": "G3SG1 | Murky",
    "B9": "G3SG1 | Orange Crash",
    "G9": "G3SG1 | Safari Mesh",
    "Nm": "G3SG1 | Scavenger",
    "BF": "G3SG1 | Stinger",
    "CZ": "G3SG1 | The Executioner",
    "Bc": "G3SG1 | Ventilator",
    "ey": "G3SG1 | Green Cell",
    "fG": "G3SG1 | Red Jasper",
#galil
    "Xk": "Galil AR | Chromatic Aberration",
    "S6": "Galil AR | Connexion",
    "aa": "Galil AR | Phoenix Blacklight",
    "Tz": "Galil AR | Vandal",
    "N9": "Galil AR | Akoben",
    "BM": "Galil AR | Black Sand",
    "FF": "Galil AR | Blue Titanium",
    "Gk": "Galil AR | Cerberus",
    "DX": "Galil AR | Chatterbox",
    "Ax": "Galil AR | Crimson Tsunami",
    "bM": "Galil AR | Destroyer",
    "DL": "Galil AR | Eco",
    "B4": "Galil AR | Firefight",
    "HB": "Galil AR | Hunting Blind",
    "ER": "Galil AR | Kami",
    "FO": "Galil AR | Orange DDPAT",
    "DH": "Galil AR | Rocket Pop",
    "Eo": "Galil AR | Sandstorm",
    "Fe": "Galil AR | Shattered",
    "Np": "Galil AR | Signal",
    "Cr": "Galil AR | Stone Cold",
    "Ae": "Galil AR | Sugar Rush",
    "d0": "Galil AR | Green Apple",
    "eF": "Galil AR | Robin\"s Egg",
    "eQ": "Galil AR | Grey Smoke",
    "ei": "Galil AR | Acid Dart",
    "fA": "Galil AR | O-Ranger",
    "fZ": "Galil AR | Control",
    "dR": "Galil AR | Mettalic Squeezer",
    "dG": "Galil AR | NV",
    "da": "Galil AR | Rainbow Spoon",
#glock
    "Xr": "Glock-18 | Clear Polymer",
    "dQ": "Glock-18 | Teal Graf",
    "cl": "Glock-18 | Gold Toof",
    "dZ": "Glock-18 | AXIA",
    "UY": "Glock-18 | Franklin",
    "ah": "Glock-18 | Gamma Doppler",
    "Tn": "Glock-18 | Neo-Noir",
    "am": "Glock-18 | Pink DDPAT",
    "Y6": "Glock-18 | Snack Attack",
    "S3": "Glock-18 | Vogue",
    "Fu": "Glock-18 | Blue Fissure",
    "Qa": "Glock-18 | Bullet Queen",
    "DG": "Glock-18 | Bunsen Burner",
    "Ou": "Glock-18 | Candy Apple",
    "Dg": "Glock-18 | Catacombs",
    "GA": "Glock-18 | Dragon Tattoo",
    "AL": "Glock-18 | Fade",
    "Dq": "Glock-18 | Grinder",
    "G4": "Glock-18 | Groundwater",
    "BK": "Glock-18 | Ironwork",
    "L2": "Glock-18 | Moonrise",
    "Gd": "Glock-18 | Night",
    "Lp": "Glock-18 | Off World",
    "Ns": "Glock-18 | Oxide Blaze",
    "b1": "Glock-18 | Ramese\"s Reach",
    "Gn": "Glock-18 | Reactor",
    "CM": "Glock-18 | Royal Legion",
    "O7": "Glock-18 | Sacrifice",
    "Ez": "Glock-18 | Steel Disruption",
    "bU": "Glock-18 | Umbral Rabbit",
    "Mo": "Glock-18 | Warhawk",
    "Bh": "Glock-18 | Wasteland Rebel",
    "D3": "Glock-18 | Water Elemental",
    "BW": "Glock-18 | Weasel",
    "bG": "Glock-18 | Winterized",
    "Cx": "Glock-18 | Wraiths",
    "cN": "Glock-18 | Block-18",
    "f9": "Glock-18 | Mirror Mosaic",
    "dw": "Glock-18 | Green Line",
    "eE": "Glock-18 | Ocean Topo",
    "eX": "Glock-18 | Glockingbird",
    "e6": "Glock-18 | Coral Bloom",
    "fU": "Glock-18 | Shinobu",
#m249
    "Gh": "M249 | Contrast Spray",
    "T2": "M249 | Deep Relief",
    "dF": "M249 | Spectrogram",
    "cy": "M249 | Hypnosis",
    "Xq": "M249 | O.S.I.P.R",
    "O5": "M249 | Aztec",
    "bF": "M249 | Downtown",
    "A1": "M249 | Emerald Poison Dart",
    "Eq": "M249 | Magma",
    "Cs": "M249 | Nebula Crusader",
    "CA": "M249 | Spectre",
    "cD": "M249 | Submerge",
    "Dh": "M249 | System Lock",
    "Pc": "M249 | Warbird",
#m4a1s
    "US": "M4A1-S | Blue Phosphor",
    "aG": "M4A1-S | Fizzy POP",
    "Zp": "M4A1-S | Imminent Danger",
    "au": "M4A1-S | Night Terror",
    "Tm": "M4A1-S | Printstream",
    "UV": "M4A1-S | Welcome to the Jungle",
    "EG": "M4A1-S | Atomic Alloy",
    "Dr": "M4A1-S | Basilisk",
    "F2": "M4A1-S | Blood Tiger",
    "Am": "M4A1-S | Briefing",
    "Fc": "M4A1-S | Bright Water",
    "Bz": "M4A1-S | Chantico\"s Fire",
    "Op": "M4A1-S | Control Panel",
    "Dz": "M4A1-S | Cyrex",
    "GC": "M4A1-S | Dark Water",
    "Au": "M4A1-S | Decimator",
    "bS": "M4A1-S | Emphorosaur-S",
    "BG": "M4A1-S | Flashback",
    "Cm": "M4A1-S | Golden Coil",
    "Eh": "M4A1-S | Guardian",
    "AD": "M4A1-S | Hot Rod",
    "DJ": "M4A1-S | Hyper Beast",
    "AK": "M4A1-S | Icarus Fell",
    "GH": "M4A1-S | Knight",
    "Lh": "M4A1-S | Leaded Glass",
    "GV": "M4A1-S | Master Piece",
    "Bi": "M4A1-S | Mecha Industries",
    "b8": "M4A1-S | Mud-Spec",
    "Mg": "M4A1-S | Nightmare",
    "AN": "M4A1-S | Nitro",
    "QZ": "M4A1-S | Player Two",
    "HG": "M4A1-S | VariCamo",
    "cJ": "M4A1-S | Black Lotus",
    "gE": "M4A1-S | Liquidation",
    "d4": "M4A1-S | Stratosphere",
    "e0": "M4A1-S | Glitched Paint",
    "e4": "M4A1-S | Rose Hex",
    "dY": "M4A1-S | Fade",
    "dV": "M4A1-S | Wash me plz",
    "ck": "M4A1-S | Vaporwave",
#m4a4
    "To": "M4A4 | Cyber Security",
    "Xg": "M4A4 | In Living Color",
    "Y9": "M4A4 | Spider Lily",
    "ai": "M4A4 | The Coalition",
    "S2": "M4A4 | Tooth Fairy",
    "Ef": "M4A4 | Asiimov",
    "Es": "M4A4 | Bullet Rain",
    "BA": "M4A4 | Buzz Kill",
    "Qu": "M4A4 | Converter",
    "ED": "M4A4 | Desert-Strike",
    "Bj": "M4A4 | Desolate Space",
    "Da": "M4A4 | Dragon King",
    "Ny": "M4A4 | Emperor",
    "DA": "M4A4 | Evil Daimyo",
    "by": "M4A4 | Eye of Horus",
    "FT": "M4A4 | Faded Zebra",
    "Ds": "M4A4 | Griffin",
    "Ad": "M4A4 | Hellfire",
    "AA": "M4A4 | Howl",
    "Nr": "M4A4 | Magnesium",
    "Lx": "M4A4 | Neo-Noir",
    "bH": "M4A4 | Poly Mag",
    "AE": "M4A4 | Poseidon",
    "HU": "M4A4 | Radiation Hazard",
    "CW": "M4A4 | Royal Paladin",
    "bO": "M4A4 | Temukau",
    "CG": "M4A4 | The Battlestar",
    "AZ": "M4A4 | Tornado",
    "E9": "M4A4 | X-Ray",
    "Fb": "M4A4 | Zirka",
    "cM": "M4A4 | Etch Lord",
    "f6": "M4A4 | Full Throttle",
    "dq": "M4A4 | Hellish",
    "eD": "M4A4 | Naval Shred Camo",
    "eY": "M4A4 | Sheet Lightning",
    "e9": "M4A4 | Steel Work",
    "fh": "M4A4 | Choppa",
    "c6": "M4A4 | Polysoup",
    "cs": "M4A4 | Turbine",
#mac10
    "S7": "MAC-10 | Allure",
    "Xp": "MAC-10 | Button Masher",
    "ab": "MAC-10 | Calf Skin",
    "Zt": "MAC-10 | Case Hardened",
    "Su": "MAC-10 | Copper Borre",
    "a2": "MAC-10 | Ensnared",
    "Ua": "MAC-10 | Gold Brick",
    "ac": "MAC-10 | Hot Snakes",
    "aI": "MAC-10 | Propaganda",
    "Y8": "MAC-10 | Toybox",
    "Aq": "MAC-10 | Aloha",
    "Gy": "MAC-10 | Amber Fade",
    "Bs": "MAC-10 | Carnivore",
    "PA": "MAC-10 | Classic Crate",
    "AO": "MAC-10 | Curse",
    "Qc": "MAC-10 | Disco Tech",
    "cA": "MAC-10 | Echoing Sands",
    "AS": "MAC-10 | Fade",
    "Fa": "MAC-10 | Graven",
    "EX": "MAC-10 | Heat",
    "GS": "MAC-10 | Indigo",
    "CR": "MAC-10 | Lapis Gator",
    "Ay": "MAC-10 | Last Dive",
    "Dc": "MAC-10 | Malachite",
    "bL": "MAC-10 | Monkeyflage",
    "DI": "MAC-10 | Neon Rider",
    "Gp": "MAC-10 | Nuclear Garden",
    "Lu": "MAC-10 | Oceanic",
    "HK": "MAC-10 | Palm",
    "Nq": "MAC-10 | Pipe Down",
    "Cy": "MAC-10 | Rangeen",
    "bW": "MAC-10 | Sakkaku",
    "PR": "MAC-10 | Stalker",
    "EI": "MAC-10 | Tatter",
    "E7": "MAC-10 | Ultraviolet",
    "OB": "MAC-10 | Whitefish",
    "cR": "MAC-10 | Light Box",
    "gD": "MAC-10 | Cat Fight",
    "dt": "MAC-10 | Derailment",
    "eO": "MAC-10 | Storm Camo",
    "ec": "MAC-10 | Poplar Thicket",
    "eh": "MAC-10 | Acid Hex",
    "fJ": "MAC-10 | Bronzer",
    "dP": "MAC-10 | Pipsqueak",
    "cr": "MAC-10 | Saiba Oni",
#mag7
    "ZD": "MAG-7 | BI83 Spectrum",
    "a4": "MAG-7 | Foresight",
    "dl": "MAG-7 | Wildwood",
    "S9": "MAG-7 | Monster Call",
    "Gx": "MAG-7 | Bulldozer",
    "QY": "MAG-7 | Cinquedea",
    "Cz": "MAG-7 | Cobalt Core",
    "b6": "MAG-7 | Copper Coated",
    "Dw": "MAG-7 | Firestarter",
    "Ar": "MAG-7 | Hard Water",
    "AR": "MAG-7 | Hazard",
    "DP": "MAG-7 | Heat",
    "Ee": "MAG-7 | Heaven Guard",
    "bd": "MAG-7 | Insomnia",
    "Ha": "MAG-7 | Irradiated Alert",
    "Qd": "MAG-7 | Justice",
    "FR": "MAG-7 | Memento",
    "BX": "MAG-7 | Petroglyph",
    "PC": "MAG-7 | Popdog",
    "CN": "MAG-7 | Praetorian",
    "GO": "MAG-7 | Silver",
    "BO": "MAG-7 | Sonar",
    "Gi": "MAG-7 | Storm",
    "L4": "MAG-7 | SWAG-7",
    "gL": "MAG-7 | MAGnitude",
    "ew": "MAG-7 | Copper Oxide",
    "fg": "MAG-7 | Resupply",
#mp5
    "Tw": "MP5-SD | Condition Zero",
    "dS": "MP5-SD | Neon Squeezer",
    "cx": "MP5-SD | Statics",
    "di": "MP5-SD | Savannah Halftone",
    "S8": "MP5-SD | Kitbash",
    "a3": "MP5-SD | Necro Jr.",
    "al": "MP5-SD | Oxide Oasis",
    "Pb": "MP5-SD | Acid Wash",
    "O3": "MP5-SD | AGent",
    "Ow": "MP5-SD | Co-Processor",
    "Qn": "MP5-SD | Desert Strike",
    "N5": "MP5-SD | Gauss",
    "bX": "MP5-SD | Liquidation",
    "Nk": "MP5-SD | Phosphor",
    "gK": "MP5-SD | Focus",
    "eU": "MP5-SD | Lime Hex",
    "eb": "MP5-SD | Gold Leaf",
#mp7
    "ar": "MP7 | Abyssal Apparition",
    "dE": "MP7 | Astrolabe",
    "ZH": "MP7 | Guerrilla",
    "A7": "MP7 | Akoben",
    "DV": "MP7 | Armor Core",
    "Ly": "MP7 | Bloodsport",
    "BL": "MP7 | Cirrus",
    "Ot": "MP7 | Fade",
    "Gc": "MP7 | Gunsmoke",
    "CO": "MP7 | Impire",
    "OC": "MP7 | Mischief",
    "C5": "MP7 | Nemesis",
    "PY": "MP7 | Neon Ply",
    "E0": "MP7 | Ocean Foam",
    "G5": "MP7 | Orange Peel",
    "Mk": "MP7 | Powercore",
    "GF": "MP7 | Skulls",
    "Ct": "MP7 | Special Delivery",
    "cE": "MP7 | Sunbaked",
    "D8": "MP7 | Urban Hazard",
    "AP": "MP7 | Whiteout",
    "cQ": "MP7 | Just Smile",
    "f8": "MP7 | Smoking Kills",
    "fF": "MP7 | Short Ochre",
#mp9
    "Gj": "MP9 | Storm",
    "dc": "MP9 | Arctic Tri-Tone",
    "Xi": "MP9 | Food Chain",
    "ZB": "MP9 | Mount Fuji",
    "aM": "MP9 | Music Box",
    "ap": "MP9 | Starlight Protector",
    "BT": "MP9 | Airlock",
    "CB": "MP9 | Bioleak",
    "MA": "MP9 | Black Sand",
    "Os": "MP9 | Bulldozer",
    "Mr": "MP9 | Capillary",
    "GK": "MP9 | Dark Age",
    "Dx": "MP9 | Dart",
    "Dj": "MP9 | Deadly Poison",
    "bY": "MP9 | Featherweight",
    "Lo": "MP9 | Goo",
    "G0": "MP9 | Hot Rod",
    "Oz": "MP9 | Hydra",
    "Fy": "MP9 | Hypnotic",
    "Nv": "MP9 | Modest Threat",
    "AU": "MP9 | Pandora\"s Box",
    "Em": "MP9 | Rose Iron",
    "C9": "MP9 | Ruby Poison Dart",
    "HQ": "MP9 | SAnd Dashed",
    "BN": "MP9 | Sand Scale",
    "Gq": "MP9 | Setting Sun",
    "Qs": "MP9 | Stained Glass",
    "Pi": "MP9 | Wild Lily",
    "gJ": "MP9 | Broken Record",
    "dp": "MP9 | Latte Rush",
    "eA": "MP9 | Cobalt Paisley",
    "eL": "MP9 | Buff Blue",
    "ep": "MP9 | Pine",
    "e7": "MP9 | Shredded",
    "fN": "MP9 | Multi-Terrain",
    "ff": "MP9 | Nexus",
#negev
    "Xn": "Negev | dev_texture",
    "Ss": "Negev | Mjolnir",
    "aR": "Negev | Phoenix Stencil",
    "dU": "Negev | Wall Bang",
    "TE": "Negev | Ultralight",
    "Md": "Negev | Anodized Navy",
    "E4": "Negev | Bratatat",
    "G1": "Negev | CaliCamo",
    "Bd": "Negev | Dazzle",
    "D9": "Negev | Desert-Strike",
    "bK": "Negev | Drop Me",
    "L6": "Negev | Lionfish",
    "C8": "Negev | Loudmouth",
    "DS": "Negev | Man-o\"-war",
    "Gt": "Negev | Nuclear Waste",
    "Cb": "Negev | Power Loader",
    "Qo": "Negev | Prototype",
    "Ec": "Negev | Terrain",
    "eH": "Negev | Sour Grapes",
    "eu": "Negev | Raw Ceramic",
#nova
    "Tv": "Nova | Clear Polymer",
    "Xu": "Nova | Windblown",
    "dO": "Nova | Wurst Holle",
    "dh": "Nova | Yorkshire",
    "EW": "Nova | Antique",
    "Ew": "Nova | Bloomstick",
    "Bt": "Nova | Exo",
    "FH": "Nova | Ghost Camo",
    "BH": "Nova | Gila",
    "F1": "Nova | Graphite",
    "GN": "Nova | Green Apple",
    "CJ": "Nova | Hyper Beast",
    "D4": "Nova | Koi",
    "Pe": "Nova | Plume",
    "HR": "Nova | Predator",
    "DF": "Nova | Ranger",
    "En": "Nova | Rising Skull",
    "b3": "Nova | Sobek\"s Bite",
    "Fi": "Nova | Tempest",
    "Mm": "Nova | Toy Soldier",
    "L5": "Nova | Wild Six",
    "Nt": "Nova | Wood Fired",
    "cX": "Nova | Dark Sigil",
    "gC": "Nova | Ocular",
    "dz": "Nova | Rain Station",
    "eK": "Nova | Turquoise Pour",
    "fP": "Nova | Marsh Grass",
    "fY": "Nova | Rising Sun",
#p2000
    "TF": "P2000 | Gnarled",
    "a5": "P2000 | Lifted Spirits",
    "Qf": "P2000 | Acid Etched",
    "dD": "P2000 | Coral Halftone",
    "HD": "P2000 | Amber Fade",
    "GL": "P2000 | Chainmail",
    "Eu": "P2000 | Corticera",
    "Dm": "P2000 | Fire Elemental",
    "Ge": "P2000 | Grassland",
    "C7": "P2000 | Handgun",
    "Cj": "P2000 | Imperial",
    "Bl": "P2000 | Imperial Dragon",
    "EC": "P2000 | Ivory",
    "PX": "P2000 | Obsidian",
    "FX": "P2000 | Ocean Foam",
    "CC": "P2000 | Oceanic",
    "EO": "P2000 | Pulse",
    "Fr": "P2000 | Red FragCam",
    "BP": "P2000 | Turf",
    "L8": "P2000 | Urban Hazard",
    "bQ": "P2000 | Wicked Sick",
    "Ah": "P2000 | Woodsman",
    "gI": "P2000 | Red Wing",
    "d8": "P2000 | Royal Baroque",
    "ek": "P2000 | Marsh",
    "fe": "P2000 | Sure Grip",
#p250
    "TC": "P250 | Cassette",
    "Tx": "P250 | Contaminant",
    "Xo": "P250 | Cyber Shell",
    "aQ": "P250 | Digital Architect",
    "aJ": "P250 | Gunsmoke",
    "Sr": "P250 | Vino Primo",
    "ao": "P250 | Whiteout",
    "b0": "P250 | Apep\"s Curse",
    "B1": "P250 | Asiimov",
    "G6": "P250 | Bone Mask",
    "Dn": "P250 | Cartel",
    "Gu": "P250 | Contamination",
    "AI": "P250 | Franklin",
    "F3": "P250 | Hive",
    "O4": "P250 | Inferno",
    "Bu": "P250 | Iron Clad",
    "Ei": "P250 | Mehndi",
    "DZ": "P250 | Muertos",
    "No": "P250 | Nevermore",
    "HT": "P250 | Nuclear Threat",
    "ba": "P250 | Re.built",
    "Aj": "P250 | Red Rock",
    "A5": "P250 | Ripple",
    "HN": "P250 | Sand Dune",
    "Lg": "P250 | See Ya Later",
    "FP": "P250 | Splash",
    "FJ": "P250 | Steel Disruption",
    "D5": "P250 | Supernova",
    "Fl": "P250 | Undertow",
    "DT": "P250 | Valence",
    "OE": "P250 | Verdigris",
    "bA": "P250 | Visions",
    "Cu": "P250 | Wingshot",
    "gH": "P250 | Bullfrog",
    "dy": "P250 | Constructivist",
    "eN": "P250 | Plum Netting",
    "er": "P250 | Copper Oxide",
    "e5": "P250 | Red Tide",
    "fE": "P250 | Sedimentary",
#p90
    "ae": "P90 | Astral Jormungandr",
    "c5": "P90 | Attack Vector",
    "cq": "P90 | Rundy Rash",
    "dT": "P90 | wash me",
    "T0": "P90 | Cocoa Rampage",
    "TB": "P90 | Freight",
    "an": "P90 | Glacier Mesh",
    "Sq": "P90 | Leather",
    "aN": "P90 | Verdant Growth",
    "D0": "P90 | Asiimov",
    "FE": "P90 | Blind Spot",
    "Bo": "P90 | Chopper",
    "Fx": "P90 | Cold Blooded",
    "FL": "P90 | Death by Kitty",
    "Ak": "P90 | Death Grip",
    "DE": "P90 | Elite Build",
    "FY": "P90 | Emerald Dragon",
    "HX": "P90 | Fallout Warning",
    "Be": "P90 | Grim",
    "EN": "P90 | Module",
    "bV": "P90 | Neoqueen",
    "O1": "P90 | Nostalgia",
    "OA": "P90 | Off World",
    "HP": "P90 | Sand Spray",
    "b2": "P90 | ScaraB Rush",
    "HA": "P90 | Scorched",
    "BC": "P90 | Shallow Grave",
    "CY": "P90 | Shapewood",
    "GQ": "P90 | Storm",
    "Mp": "P90 | Traction",
    "EV": "P90 | Trigon",
    "bE": "P90 | Vent Rush",
    "E2": "P90 | Virus",
    "d1": "P90 | Straight Dimes",
    "eB": "P90 | Reef Grief",
    "eR": "P90 | Blue Tac",
    "ej": "P90 | Mustard Gas",
    "fQ": "P90 | Desert Halftone",
    "fX": "P90 | Wave Breaker",
#pp bizon
    "dj": "PP-Bizon | Cold Cell",
    "ZI": "PP-Bizon | Lumen",
    "TD": "PP-Bizon | Runic",
    "ax": "PP-Bizon | Space Cat",
    "EK": "PP-Bizon | Antique",
    "E1": "PP-Bizon | Blue Streak",
    "HF": "PP-Bizon | Brass",
    "Gs": "PP-Bizon | Chemical Green",
    "Er": "PP-Bizon | Cobalt Halftone",
    "PZ": "PP-Bizon | Embargo",
    "Ca": "PP-Bizon | Fuel Rod",
    "Bv": "PP-Bizon | Harvester",
    "Lj": "PP-Bizon | High Roller",
    "HY": "PP-Bizon | Irradiated Alert",
    "By": "PP-Bizon | Judgement of Anubis",
    "A6": "PP-Bizon | Jungle Slipstream",
    "MB": "PP-Bizon | Night Riot",
    "D6": "PP-Bizon | Osiris",
    "CP": "PP-Bizon | Photic Zone",
    "FG": "PP-Bizon | Water Sigil",
    "fM": "PP-Bizon | Wood Block Camo",
#r8
    "bT": "R8 Revolver | Banana Cannon",
    "aL": "R8 Revolver | Blaze",
    "Xv": "R8 Revolver | Junk Yard",
    "HC": "R8 Revolver | Amber Fade",
    "Qm": "R8 Revolver | Bone Forged",
    "bB": "R8 Revolver | Crazy 8",
    "Cg": "R8 Revolver | Crimson Web",
    "CV": "R8 Revolver | Fade",
    "cw": "R8 Revolver | Tango",
    "L7": "R8 Revolver | Grip",
    "cC": "R8 Revolver | Inlay",
    "Li": "R8 Revolver | Llama Cannon",
    "Pg": "R8 Revolver | Memento",
    "Bq": "R8 Revolver | Reboot",
    "N2": "R8 Revolver | Skull Crusher",
    "Mt": "R8 Revolver | Survivalist",
    "eS": "R8 Revolver | Cobalt Grip",
    "el": "R8 Revolver | Leafhopper",
#scar
    "a0": "SCAR-20 | Poultrygeist",
    "cv": "SCAR-20 | Trail Blazer",
    "dA": "SCAR-20 | Wild Berry",
    "PD": "SCAR-20 | Assault",
    "Bk": "SCAR-20 | Bloodsport",
    "A4": "SCAR-20 | Blueprint",
    "Do": "SCAR-20 | Cardiac",
    "F6": "SCAR-20 | Crimson Web",
    "EH": "SCAR-20 | Cyrex",
    "Qh": "SCAR-20 | Enforcer",
    "bZ": "SCAR-20 | Fragments",
    "C0": "SCAR-20 | Green Marine",
    "Dk": "SCAR-20 | Grotto",
    "Lt": "SCAR-20 | Jungle Slipstream",
    "Cl": "SCAR-20 | Outbreak",
    "BY": "SCAR-20 | Powercore",
    "HO": "SCAR-20 | Sand Mesh",
    "GT": "SCAR-20 | Storm",
    "gG": "SCAR-20 | Caged",
    "fI": "SCAR-20 | Short Ochre",
#sg
    "Xw": "SG 553 | Heavy Metal",
    "c9": "SG 553 | Berry Gel Coat",
    "TG": "SG 553 | Ol\" Rusty",
    "Sn": "SG 553 | Traveler",
    "Bx": "SG 553 | Aerial",
    "MC": "SG 553 | Aloha",
    "CE": "SG 553 | Atlas",
    "PS": "SG 553 | Colony IV",
    "bb": "SG 553 | Cyberforce",
    "C4": "SG 553 | Cyrex",
    "HE": "SG 553 | Damascus Steel",
    "Nu": "SG 553 | Danger Close",
    "Qe": "SG 553 | Darkwing",
    "bD": "SG 553 | Dragon Tech",
    "Gw": "SG 553 | Fallout Warning",
    "G3": "SG 553 | Gator Mesh",
    "QV": "SG 553 | Integrale",
    "Lm": "SG 553 | Phantom",
    "EY": "SG 553 | Pulse",
    "Cd": "SG 553 | Tiger Moth",
    "BZ": "SG 553 | Triarch",
    "GE": "SG 553 | Ultraviolet",
    "Ff": "SG 553 | Wave Spray",
    "eT": "SG 553 | Night Camo",
    "fC": "SG 553 | Basket Halftone",
#ssg
    "aP": "SSG 08 | Death Strike",
    "df": "SSG 08 | Zeno",
    "cp": "SSG 08 | Rapid Transit",
    "dC": "SSG 08 | Halftone Whorl",
    "TA": "SSG 08 | Mainframe 001",
    "Ts": "SSG 08 | Parallax",
    "Sx": "SSG 08 | Sea Calico",
    "Y7": "SSG 08 | Turbo Peek",
    "EA": "SSG 08 | Abyss",
    "cB": "SSG 08 | Azure Glyph",
    "Cq": "SSG 08 | Big Iron",
    "Fv": "SSG 08 | Blood in the Water",
    "PT": "SSG 08 | Bloodshot",
    "E8": "SSG 08 | Dark Water",
    "Ai": "SSG 08 | Death\"s Head",
    "Ga": "SSG 08 | Detour",
    "A9": "SSG 08 | Dragonfire",
    "Qg": "SSG 08 | Fever Dream",
    "B5": "SSG 08 | Ghost Crusader",
    "CS": "SSG 08 | Necropos",
    "EQ": "SSG 08 | Slashed",
    "G2": "SSG 08 | Tropical Storm",
    "cS": "SSG 08 | Dezastre",
    "eP": "SSG 08 | Grey Smoke",
    "ef": "SSG 08 | Tiger Tear",
    "es": "SSG 08 | Green Ceramic",
    "e8": "SSG 08 | Blush Pour",
    "fd": "SSG 08 | Memorial",
#sawed off
    "Sv": "Sawed-Off | Copper",
    "az": "Sawed-Off | Spirit Board",
    "Qi": "Sawed-Off | Apocalypto",
    "Nw": "Sawed-Off | Black Sand",
    "Mh": "Sawed-Off | Devourer",
    "CD": "Sawed-Off | Fubar",
    "Dt": "Sawed-Off | Highwayman",
    "HZ": "Sawed-Off | Irradiated Alert",
    "a9": "Sawed-Off | Kiss♥Love",
    "Bp": "Sawed-Off | Limelight",
    "Lv": "Sawed-Off | Morris",
    "FQ": "Sawed-Off | Orange DDPAT",
    "DR": "Sawed-Off | Origami",
    "GP": "Sawed-Off | Rust Coat",
    "Gf": "Sawed-Off | Sage Spray",
    "Dd": "Sawed-Off | Serenity",
    "HH": "Sawed-Off | Snake Camo",
    "Eg": "Sawed-Off | The Kraken",
    "BD": "Sawed-Off | Wasteland Princess",
    "Ck": "Sawed-Off | Yorick",
    "A8": "Sawed-Off | Zander",
    "cP": "Sawed-Off | Analog Input",
    "eV": "Sawed-Off | Runoff",
#tec9
    "S5": "Tec-9 | Brother",
    "dk": "Tec-9 | Tiger Stencil",
    "Ce": "Tec-9 | Avalanche",
    "N7": "Tec-9 | Bamboozle",
    "F5": "Tec-9 | Blue Titanium",
    "Ls": "Tec-9 | Cracked Opal",
    "An": "Tec-9 | Cut Out",
    "PU": "Tec-9 | Decimator",
    "PB": "Tec-9 | Flash Out",
    "Nx": "Tec-9 | Fubar",
    "BU": "Tec-9 | Fuel Injector",
    "Bw": "Tec-9 | Ice Cap",
    "EP": "Tec-9 | Isaac",
    "CT": "Tec-9 | Jambiya",
    "b7": "Tec-9 | Mummy\"s Rot",
    "HS": "Tec-9 | Nuclear Threat",
    "B6": "Tec-9 | Re-Entry",
    "bc": "Tec-9 | Rebel",
    "Ed": "Tec-9 | Sandstorm",
    "Mq": "Tec-9 | Snek-9",
    "AW": "Tec-9 | Terrace",
    "Fn": "Tec-9 | Titanium Bit",
    "Gm": "Tec-9 | Toxic",
    "HL": "Tec-9 | VariCamo",
    "cT": "Tec-9 | Slag",
    "ds": "Tec-9 | Whiteout",
    "eM": "Tec-9 | Blue Blast",
    "eg": "Tec-9 | Garter-9",
    "et": "Tec-9 | Raw Ceramic",
    "fD": "Tec-9 | Citric Acid",
#ump
    "UZ": "UMP-45 | Crime Scene",
    "Zs": "UMP-45 | Fade",
    "cm": "UMP-45 | Neo-Noir",
    "db": "UMP-45 | Crimson Foil",
    "Tt": "UMP-45 | Gold Bismuth",
    "Xs": "UMP-45 | Oscillator",
    "L3": "UMP-45 | Arctic Wolf",
    "Gz": "UMP-45 | Blaze",
    "Fg": "UMP-45 | Bone Pile",
    "Bf": "UMP-45 | Briefing",
    "Eb": "UMP-45 | Corporal",
    "Dy": "UMP-45 | Delusion",
    "Ll": "UMP-45 | Exposure",
    "HW": "UMP-45 | Fallout Warning",
    "DN": "UMP-45 | Grand Prix",
    "GR": "UMP-45 | Indigo",
    "EB": "UMP-45 | Labyrinth",
    "Ap": "UMP-45 | Metal Flowers",
    "AT": "UMP-45 | Minotaur\"s Labyrinth",
    "Nl": "UMP-45 | Momentum",
    "N6": "UMP-45 | Moonrise",
    "O2": "UMP-45 | Plastique",
    "B2": "UMP-45 | Primal Saber",
    "DD": "UMP-45 | Riot",
    "bJ": "UMP-45 | Roadblock",
    "A0": "UMP-45 | Scaffold",
    "Gg": "UMP-45 | Scorched",
    "bR": "UMP-45 | Wild Child",
    "cU": "UMP-45 | Motorized",
    "gB": "UMP-45 | Continuum",
    "dv": "UMP-45 | Late Night Transit",
    "eo": "UMP-45 | Green Swirl",
    "fT": "UMP-45 | K.O. Factory",
#usps
    "AH": "USP-S | Orion",
    "ZE": "USP-S | Black Lotus",
    "cu": "USP-S | 027",
    "de": "USP-S | Alphine Camo",
    "Sp": "USP-S | Business Class",
    "Tp": "USP-S | Monster Mashup",
    "a6": "USP-S | Printstream",
    "UT": "USP-S | Target Acquired",
    "Xh": "USP-S | The Traitor",
    "av": "USP-S | Ticket to Hell",
    "ag": "USP-S | Whiteout",
    "E6": "USP-S | Blood Tiger",
    "Al": "USP-S | Blueprint",
    "EF": "USP-S | Caiman",
    "L0": "USP-S | Cortex",
    "BI": "USP-S | Cyrex",
    "GB": "USP-S | Dark Water",
    "b9": "USP-S | Desert Tactical",
    "Nn": "USP-S | Flashback",
    "Ea": "USP-S | Guardian",
    "Cn": "USP-S | Kill Confirmed",
    "CU": "USP-S | Lead Conduit",
    "At": "USP-S | Neo-Noir",
    "FZ": "USP-S | Overgrowth",
    "GX": "USP-S | Road Rash",
    "GM": "USP-S | Royal Blue",
    "Fw": "USP-S | Serum",
    "Ft": "USP-S | Stainless",
    "DC": "USP-S | Torque",
    "cL": "USP-S | Jawbreaker",
    "d6": "USP-S | Royal Guard",
    "ea": "USP-S | Tropical Breeze",
    "e2": "USP-S | Bleeding Edge",
    "fc": "USP-S | PC-GRN",
#xm1014
    "S4": "XM1014 | Entombed",
    "c8": "XM1014 | Halftone Shift",
    "dL": "XM1014 | Monster Melt",
    "St": "XM1014 | Frost Borre",
    "So": "XM1014 | Red Leather",
    "ZF": "XM1014 | Watchdog",
    "Xj": "XM1014 | XOXO",
    "ay": "XM1014 | Zombie Offensive",
    "B7": "XM1014 | Black Tie",
    "Go": "XM1014 | Bone Machine",
    "HV": "XM1014 | Fallout Warning",
    "EL": "XM1014 | Heaven Guard",
    "cF": "XM1014 | Hieroglyph",
    "N0": "XM1014 | Incinegator",
    "MD": "XM1014 | Oxide Blaze",
    "Di": "XM1014 | Quicksilver",
    "E3": "XM1014 | Red Python",
    "C1": "XM1014 | Scumbria",
    "Az": "XM1014 | Seasons",
    "Bg": "XM1014 | Slipstream",
    "Cf": "XM1014 | Teclu Burner",
    "Dp": "XM1014 | Tranquility",
    "GZ": "XM1014 | VariCamo Blue",
    "Ln": "XM1014 | Ziggy",
    "cV": "XM1014 | Irezumi",
    "du": "XM1014 | Run Run Run",
    "eJ": "XM1014 | Gum Wall Camo",
    "ed": "XM1014 | Copperflage",
    "fO": "XM1014 | Canvas Cloud",
    "fb": "XM1014 | Mockingbird",
#zeus
    "cK": "Zeus x27 | Olympus",
    "dr": "Zeus x27 | Charged Up",
    "dJ": "Zeus x27 | Dragon Snore",
    "eC": "Zeus x27 | Electric Blue",
    "en": "Zeus x27 | Swamp DDPAT",
    "fW": "Zeus x27 | Tosai",
#                                                                                            KNIFES
#karambit
    "Wm": "Karambit | Case Hardened (Blue Gem)",
    "Wn": "Karambit | Case Hardened (Gold Gem)",
    "JA": "Karambit | Doppler",
    "VV": "Karambit | Doppler (Black Pearl)",
    "VW": "Karambit | Doppler (Phase 1)",
    "VX": "Karambit | Doppler (Phase 2)",
    "VY": "Karambit | Doppler (Phase 3)",
    "VZ": "Karambit | Doppler (Phase 4)",
    "Va": "Karambit | Doppler (Ruby)",
    "Vb": "Karambit | Doppler (Sapphire)",
    "I5": "Karambit | Gamma Doppler",
    "Vr": "Karambit | Gamma Doppler (Emerald)",
    "Vs": "Karambit | Gamma Doppler (Phase 1)",
    "Vt": "Karambit | Gamma Doppler (Phase 2)",
    "Vu": "Karambit | Gamma Doppler (Phase 3)",
    "Vv": "Karambit | Gamma Doppler (Phase 4)",
    "I6": "Karambit | Autotronic",
    "I4": "Karambit | Black Laminate",
    "JF": "Karambit | Blue Steel",
    "JG": "Karambit | Boreal Forest",
    "I7": "Karambit | Bright Water",
    "JH": "Karambit | Case Hardened",
    "JI": "Karambit | Crimson Web",
    "I9": "Karambit | Damascus Steel",
    "JJ": "Karambit | Fade",
    "JK": "Karambit | Forest DDPAT",
    "I8": "Karambit | Freehand",
    "I3": "Karambit | Lore",
    "JB": "Karambit | Marble Fade",
    "JL": "Karambit | Night",
    "JD": "Karambit | Rust Coat",
    "JM": "Karambit | Safari Mesh",
    "JN": "Karambit | Scorched",
    "JO": "Karambit | Slaughter",
    "JP": "Karambit | Stained",
    "JC": "Karambit | Tiger Tooth",
    "JE": "Karambit | Ultraviolet",
    "JQ": "Karambit | Urban Masked",
#butterfly
    "J8": "Butterfly Knife | Doppler",
    "V8": "Butterfly Knife | Doppler (Black Pearl)",
    "V9": "Butterfly Knife | Doppler (Phase 1)",
    "WA": "Butterfly Knife | Doppler (Phase 2)",
    "WB": "Butterfly Knife | Doppler (Phase 3)",
    "WC": "Butterfly Knife | Doppler (Phase 4)",
    "WD": "Butterfly Knife | Doppler (Ruby)",
    "WE": "Butterfly Knife | Doppler (Sapphire)",
    "ZW": "Butterfly Knife | Gamma Doppler",
    "ZS": "Butterfly Knife | Autotronic",
    "ZU": "Butterfly Knife | Black Laminate",
    "ZT": "Butterfly Knife | Bright Water",
    "Wq": "Butterfly Knife | Case Hardened (Blue Gem)",
    "Wr": "Butterfly Knife | Case Hardened (Gold Gem)",
    "ZV": "Butterfly Knife | Freehand",
    "ZR": "Butterfly Knife | Lore",
    "KH": "Butterfly Knife | Blue Steel",
    "KL": "Butterfly Knife | Boreal Forest",
    "KG": "Butterfly Knife | Case Hardened",
    "KF": "Butterfly Knife | Crimson Web",
    "J7": "Butterfly Knife | Damascus Steel",
    "KD": "Butterfly Knife | Fade",
    "KO": "Butterfly Knife | Forest DDPAT",
    "KB": "Butterfly Knife | Marble Fade",
    "KI": "Butterfly Knife | Night",
    "KA": "Butterfly Knife | Rust Coat",
    "KK": "Butterfly Knife | Safari Mesh",
    "KN": "Butterfly Knife | Scorched",
    "KE": "Butterfly Knife | Slaughter",
    "KJ": "Butterfly Knife | Stained",
    "KC": "Butterfly Knife | Tiger Tooth",
    "J9": "Butterfly Knife | Ultraviolet",
    "KM": "Butterfly Knife | Urban Masked",
#flip
    "IP": "Flip Knife | Doppler",
    "VA": "Flip Knife | Doppler (Black Pearl)",
    "VB": "Flip Knife | Doppler (Phase 1)",
    "VC": "Flip Knife | Doppler (Phase 2)",
    "VD": "Flip Knife | Doppler (Phase 3)",
    "VE": "Flip Knife | Doppler (Phase 4)",
    "VF": "Flip Knife | Doppler (Ruby)",
    "VG": "Flip Knife | Doppler (Sapphire)",
    "IJ": "Flip Knife | Gamma Doppler",
    "Vh": "Flip Knife | Gamma Doppler (Emerald)",
    "Vi": "Flip Knife | Gamma Doppler (Phase 1)",
    "Vj": "Flip Knife | Gamma Doppler (Phase 2)",
    "Vk": "Flip Knife | Gamma Doppler (Phase 3)",
    "Vl": "Flip Knife | Gamma Doppler (Phase 4)",
    "IK": "Flip Knife | Autotronic",
    "II": "Flip Knife | Black Laminate",
    "IT": "Flip Knife | Blue Steel",
    "IY": "Flip Knife | Forest DDPAT",
    "IU": "Flip Knife | Boreal Forest",
    "IL": "Flip Knife | Bright Water",
    "IX": "Flip Knife | Case Hardened",
    "IM": "Flip Knife | Damascus Steel",
    "IV": "Flip Knife | Fade",
    "IW": "Flip Knife | Crimson Web",
    "IN": "Flip Knife | Freehand",
    "IH": "Flip Knife | Lore",
    "IO": "Flip Knife | Marble Fade",
    "IZ": "Flip Knife | Night",
    "IR": "Flip Knife | Rust Coat",
    "Ia": "Flip Knife | Safari Mesh",
    "Ib": "Flip Knife | Scorched",
    "Ic": "Flip Knife | Slaughter",
    "Id": "Flip Knife | Stained",
    "IQ": "Flip Knife | Tiger Tooth",
    "IS": "Flip Knife | Ultraviolet",
    "Ie": "Flip Knife | Urban Masked",
#navaja
    "OI": "Navaja Knife | Doppler",
    "Ub": "Navaja Knife | Doppler (Black Pearl)",
    "Uf": "Navaja Knife | Doppler (Phase 1)",
    "Ue": "Navaja Knife | Doppler (Phase 2)",
    "Ud": "Navaja Knife | Doppler (Phase 3)",
    "Uc": "Navaja Knife | Doppler (Phase 4)",
    "Ug": "Navaja Knife | Doppler (Ruby)",
    "Uh": "Navaja Knife | Doppler (Sapphire)",
    "OQ": "Navaja Knife | Blue Steel",
    "OS": "Navaja Knife | Boreal Forest",
    "OP": "Navaja Knife | Case Hardened",
    "OO": "Navaja Knife | Crimson Web",
    "OH": "Navaja Knife | Damascus Steel",
    "OL": "Navaja Knife | Fade",
    "OW": "Navaja Knife | Forest DDPAT",
    "OG": "Navaja Knife | Marble Fade",
    "OU": "Navaja Knife | Night Stripe",
    "OK": "Navaja Knife | Rust Coat",
    "OV": "Navaja Knife | Safari Mesh",
    "OT": "Navaja Knife | Scorched",
    "OM": "Navaja Knife | Slaughter",
    "OR": "Navaja Knife | Stained",
    "OF": "Navaja Knife | Tiger Tooth",
    "OJ": "Navaja Knife | Ultraviolet",
    "ON": "Navaja Knife | Urban Masked",
#stiletto
    "OX": "Stiletto Knife | Doppler",
    "Ui": "Stiletto Knife | Doppler (Black Pearl)",
    "Uj": "Stiletto Knife | Doppler (Phase 1)",
    "Uk": "Stiletto Knife | Doppler (Phase 2)",
    "Ul": "Stiletto Knife | Doppler (Phase 3)",
    "Um": "Stiletto Knife | Doppler (Phase 4)",
    "Un": "Stiletto Knife | Doppler (Ruby)",
    "Uo": "Stiletto Knife | Doppler (Sapphire)",
    "NA": "Stiletto Knife | Blue Steel",
    "NF": "Stiletto Knife | Boreal Forest",
    "NI": "Stiletto Knife | Case Hardened",
    "M9": "Stiletto Knife | Crimson Web",
    "OZ": "Stiletto Knife | Damascus Steel",
    "M7": "Stiletto Knife | Fade",
    "NB": "Stiletto Knife | Forest DDPAT",
    "OY": "Stiletto Knife | Marble Fade",
    "ND": "Stiletto Knife | Night Stripe",
    "Oc": "Stiletto Knife | Rust Coat",
    "NG": "Stiletto Knife | Safari Mesh",
    "NE": "Stiletto Knife | Scorched",
    "M8": "Stiletto Knife | Slaughter",
    "NC": "Stiletto Knife | Stained",
    "Ob": "Stiletto Knife | Tiger Tooth",
    "Oa": "Stiletto Knife | Ultraviolet",
    "NH": "Stiletto Knife | Urban Masked",
#talon
    "Oe": "Talon Knife | Doppler",
    "Up": "Talon Knife | Doppler (Black Pearl)",
    "Uq": "Talon Knife | Doppler (Phase 1)",
    "Ur": "Talon Knife | Doppler (Phase 2)",
    "Us": "Talon Knife | Doppler (Phase 3)",
    "Ut": "Talon Knife | Doppler (Phase 4)",
    "Uu": "Talon Knife | Doppler (Ruby)",
    "Uv": "Talon Knife | Doppler (Sapphire)",
    "NK": "Talon Knife | Blue Steel",
    "NU": "Talon Knife | Boreal Forest",
    "NN": "Talon Knife | Case Hardened",
    "NL": "Talon Knife | Crimson Web",
    "Og": "Talon Knife | Damascus Steel",
    "NM": "Talon Knife | Fade",
    "NO": "Talon Knife | Forest DDPAT",
    "Od": "Talon Knife | Marble Fade",
    "NT": "Talon Knife | Night Stripe",
    "Oh": "Talon Knife | Rust Coat",
    "NP": "Talon Knife | Safari Mesh",
    "NQ": "Talon Knife | Scorched",
    "NJ": "Talon Knife | Slaughter",
    "NS": "Talon Knife | Stained",
    "Of": "Talon Knife | Tiger Tooth",
    "Oi": "Talon Knife | Ultraviolet",
    "NR": "Talon Knife | Urban Masked",
#nomad
    "fx": "Nomad Knife | Doppler",
    "fu": "Nomad Knife | Tiger Tooth",
    "fv": "Nomad Knife | Rust Coat",
    "fw": "Nomad Knife | Marble Fade",
    "f4": "Nomad Knife | Ultraviolet",
    "f5": "Nomad Knife | Damascus Steel",
    "QP": "Nomad Knife | Blue Steel",
    "QN": "Nomad Knife | Boreal Forest",
    "QO": "Nomad Knife | Case Hardened",
    "QL": "Nomad Knife | Crimson Web",
    "QJ": "Nomad Knife | Fade",
    "QR": "Nomad Knife | Forest DDPAT",
    "QT": "Nomad Knife | Night Stripe",
    "QU": "Nomad Knife | Safari Mesh",
    "QQ": "Nomad Knife | Scorched",
    "QK": "Nomad Knife | Slaughter",
    "QS": "Nomad Knife | Stained",
    "QM": "Nomad Knife | Urban Masked",
#ursus
    "Ol": "Ursus Knife | Doppler",
    "Uw": "Ursus Knife | Doppler (Black Pearl)",
    "Ux": "Ursus Knife | Doppler (Phase 1)",
    "Uy": "Ursus Knife | Doppler (Phase 2)",
    "Uz": "Ursus Knife | Doppler (Phase 3)",
    "U0": "Ursus Knife | Doppler (Phase 4)",
    "U1": "Ursus Knife | Doppler (Ruby)",
    "U2": "Ursus Knife | Doppler (Sapphire)",
    "NW": "Ursus Knife | Blue Steel",
    "Nd": "Ursus Knife | Boreal Forest",
    "NX": "Ursus Knife | Case Hardened",
    "Nf": "Ursus Knife | Crimson Web",
    "On": "Ursus Knife | Damascus Steel",
    "Ng": "Ursus Knife | Fade",
    "NZ": "Ursus Knife | Forest DDPAT",
    "Ok": "Ursus Knife | Marble Fade",
    "Nb": "Ursus Knife | Night Stripe",
    "Oo": "Ursus Knife | Rust Coat",
    "NY": "Ursus Knife | Safari Mesh",
    "Ne": "Ursus Knife | Scorched",
    "NV": "Ursus Knife | Slaughter",
    "Nc": "Ursus Knife | Stained",
    "Oj": "Ursus Knife | Tiger Tooth",
    "Om": "Ursus Knife | Ultraviolet",
    "Na": "Ursus Knife | Urban Masked",
#classic
    "PJ": "Classic Knife | Blue Steel",
    "PK": "Classic Knife | Boreal Forest",
    "PH": "Classic Knife | Case Hardened",
    "PG": "Classic Knife | Crimson Web",
    "PE": "Classic Knife | Fade",
    "PI": "Classic Knife | Forest DDPAT",
    "PL": "Classic Knife | Night Stripe",
    "PM": "Classic Knife | Safari Mesh",
    "PO": "Classic Knife | Scorched",
    "PF": "Classic Knife | Slaughter",
    "PN": "Classic Knife | Stained",
    "PP": "Classic Knife | Urban Masked",
    "Wx": "Classic Knife | Case Hardened (Gold Gem)",
#falchion
    "KT": "Falchion Knife | Doppler",
    "WF": "Falchion Knife | Doppler (Black Pearl)",
    "WG": "Falchion Knife | Doppler (Phase 1)",
    "WH": "Falchion Knife | Doppler (Phase 2)",
    "WI": "Falchion Knife | Doppler (Phase 3)",
    "WJ": "Falchion Knife | Doppler (Phase 4)",
    "WK": "Falchion Knife | Doppler (Ruby)",
    "WL": "Falchion Knife | Doppler (Sapphire)",
    "ZY": "Falchion Knife | Gamma Doppler",
    "ZX": "Falchion Knife | Autotronic",
    "Zb": "Falchion Knife | Black Laminate",
    "Zc": "Falchion Knife | Bright Water",
    "Ws": "Falchion Knife | Case Hardened (Blue Gem)",
    "Wt": "Falchion Knife | Case Hardened (Gold Gem)",
    "ZZ": "Falchion Knife | Freehand",
    "Za": "Falchion Knife | Lore",
    "Ka": "Falchion Knife | Blue Steel",
    "Kd": "Falchion Knife | Boreal Forest",
    "KZ": "Falchion Knife | Case Hardened",
    "KX": "Falchion Knife | Crimson Web",
    "KQ": "Falchion Knife | Damascus Steel",
    "KV": "Falchion Knife | Fade",
    "Kf": "Falchion Knife | Forest DDPAT",
    "KU": "Falchion Knife | Marble Fade",
    "KY": "Falchion Knife | Night",
    "KR": "Falchion Knife | Rust Coat",
    "Kg": "Falchion Knife | Safari Mesh",
    "Ke": "Falchion Knife | Scorched",
    "KW": "Falchion Knife | Slaughter",
    "Kb": "Falchion Knife | Stained",
    "KP": "Falchion Knife | Tiger Tooth",
    "KS": "Falchion Knife | Ultraviolet",
    "Kc": "Falchion Knife | Urban Masked",
#skeleton
    "fp": "Skeleton Knife | Doppler",
    "fm": "Skeleton Knife | Tiger Tooth",
    "fn": "Skeleton Knife | Rust Coat",
    "fo": "Skeleton Knife | Marble Fade",
    "f0": "Skeleton Knife | Ultraviolet",
    "f1": "Skeleton Knife | Damascus Steel",
    "QB": "Skeleton Knife | Blue Steel",
    "QF": "Skeleton Knife | Boreal Forest",
    "P9": "Skeleton Knife | Case Hardened",
    "P8": "Skeleton Knife | Crimson Web",
    "P7": "Skeleton Knife | Fade",
    "QE": "Skeleton Knife | Forest DDPAT",
    "QD": "Skeleton Knife | Night Stripe",
    "QG": "Skeleton Knife | Safari Mesh",
    "QI": "Skeleton Knife | Scorched",
    "QA": "Skeleton Knife | Slaughter",
    "QC": "Skeleton Knife | Stained",
    "QH": "Skeleton Knife | Urban Masked",
    "Wy": "Skeleton Knife | Case Hardened (Blue Gem)",
    "Wz": "Skeleton Knife | Case Hardened (Gold Gem)",
#m9 bayo
    "JY": "M9 Bayonet | Doppler",
    "VO": "M9 Bayonet | Doppler (Black Pearl)",
    "VP": "M9 Bayonet | Doppler (Phase 1)",
    "VQ": "M9 Bayonet | Doppler (Phase 2)",
    "VR": "M9 Bayonet | Doppler (Phase 3)",
    "VS": "M9 Bayonet | Doppler (Phase 4)",
    "VT": "M9 Bayonet | Doppler (Ruby)",
    "VU": "M9 Bayonet | Doppler (Sapphire)",
    "JT": "M9 Bayonet | Gamma Doppler",
    "Vw": "M9 Bayonet | Gamma Doppler (Emerald)",
    "Vx": "M9 Bayonet | Gamma Doppler (Phase 1)",
    "Vy": "M9 Bayonet | Gamma Doppler (Phase 2)",
    "Vz": "M9 Bayonet | Gamma Doppler (Phase 3)",
    "V0": "M9 Bayonet | Gamma Doppler (Phase 4)",
    "JU": "M9 Bayonet | Autotronic",
    "JS": "M9 Bayonet | Black Laminate",
    "Jd": "M9 Bayonet | Blue Steel",
    "Je": "M9 Bayonet | Boreal Forest",
    "JV": "M9 Bayonet | Bright Water",
    "Jf": "M9 Bayonet | Case Hardened",
    "Jg": "M9 Bayonet | Crimson Web",
    "JX": "M9 Bayonet | Damascus Steel",
    "Jh": "M9 Bayonet | Fade",
    "Ji": "M9 Bayonet | Forest DDPAT",
    "JW": "M9 Bayonet | Freehand",
    "JR": "M9 Bayonet | Lore",
    "JZ": "M9 Bayonet | Marble Fade",
    "Jj": "M9 Bayonet | Night",
    "Jb": "M9 Bayonet | Rust Coat",
    "Jk": "M9 Bayonet | Safari Mesh",
    "Jl": "M9 Bayonet | Scorched",
    "Jm": "M9 Bayonet | Slaughter",
    "Jn": "M9 Bayonet | Stained",
    "Ja": "M9 Bayonet | Tiger Tooth",
    "Jc": "M9 Bayonet | Ultraviolet",
    "Jo": "M9 Bayonet | Urban Masked",
    "W1": "M9 Bayonet | Case Hardened (Blue Gem)",
#bowie
    "K2": "Bowie Knife | Doppler",
    "V1": "Bowie Knife | Doppler (Black Pearl)",
    "V2": "Bowie Knife | Doppler (Phase 1)",
    "V3": "Bowie Knife | Doppler (Phase 2)",
    "V4": "Bowie Knife | Doppler (Phase 3)",
    "V5": "Bowie Knife | Doppler (Phase 4)",
    "V6": "Bowie Knife | Doppler (Ruby)",
    "V7": "Bowie Knife | Doppler (Sapphire)",
    "ZL": "Bowie Knife | Gamma Doppler",
    "LA": "Bowie Knife | Night",
    "ZO": "Bowie Knife | Autotronic",
    "ZQ": "Bowie Knife | Black Laminate",
    "ZP": "Bowie Knife | Bright Water",
    "ZN": "Bowie Knife | Freehand",
    "ZM": "Bowie Knife | Lore",
    "LC": "Bowie Knife | Blue Steel",
    "K9": "Bowie Knife | Boreal Forest",
    "K7": "Bowie Knife | Case Hardened",
    "K8": "Bowie Knife | Crimson Web",
    "K1": "Bowie Knife | Damascus Steel",
    "K6": "Bowie Knife | Fade",
    "LE": "Bowie Knife | Forest DDPAT",
    "K3": "Bowie Knife | Marble Fade",
    "K0": "Bowie Knife | Rust Coat",
    "LG": "Bowie Knife | Safari Mesh",
    "LD": "Bowie Knife | Scorched",
    "K5": "Bowie Knife | Slaughter",
    "LB": "Bowie Knife | Stained",
    "K4": "Bowie Knife | Tiger Tooth",
    "Kz": "Bowie Knife | Ultraviolet",
    "LF": "Bowie Knife | Urban Masked",
#paracord
    "ft": "Paracord Knife | Doppler",
    "fq": "Paracord Knife | Tiger Tooth",
    "fr": "Paracord Knife | Rust Coat",
    "fs": "Paracord Knife | Marble Fade",
    "f2": "Paracord Knife | Ultraviolet",
    "f3": "Paracord Knife | Damascus Steel",
    "Pp": "Paracord Knife | Blue Steel",
    "Pq": "Paracord Knife | Boreal Forest",
    "Pn": "Paracord Knife | Case Hardened",
    "Pm": "Paracord Knife | Crimson Web",
    "Pk": "Paracord Knife | Fade",
    "Pu": "Paracord Knife | Forest DDPAT",
    "Pl": "Paracord Knife | Night Stripe",
    "Ps": "Paracord Knife | Safari Mesh",
    "Pt": "Paracord Knife | Scorched",
    "Pj": "Paracord Knife | Slaughter",
    "Po": "Paracord Knife | Stained",
    "Pr": "Paracord Knife | Urban Masked",
#daggers
    "Ki": "Shadow Daggers Knife | Doppler",
    "WT": "Shadow Daggers Knife | Doppler (Black Pearl)",
    "WU": "Shadow Daggers Knife | Doppler (Phase 1)",
    "WV": "Shadow Daggers Knife | Doppler (Phase 2)",
    "WW": "Shadow Daggers Knife | Doppler (Phase 3)",
    "WX": "Shadow Daggers Knife | Doppler (Phase 4)",
    "WY": "Shadow Daggers Knife | Doppler (Ruby)",
    "WZ": "Shadow Daggers Knife | Doppler (Sapphire)",
    "Zm": "Shadow Daggers Knife | Gamma Doppler",
    "Zk": "Shadow Daggers Knife | Autotronic",
    "Zl": "Shadow Daggers Knife | Black Laminate",
    "Zn": "Shadow Daggers Knife | Bright Water",
    "Wu": "Shadow Daggers Knife | Case Hardened (Blue Gem)",
    "Zj": "Shadow Daggers Knife | Freehand",
    "Zo": "Shadow Daggers Knife | Lore",
    "Ks": "Shadow Daggers Knife | Blue Steel",
    "Kx": "Shadow Daggers Knife | Boreal Forest",
    "Kq": "Shadow Daggers Knife | Case Hardened",
    "Ko": "Shadow Daggers Knife | Crimson Web",
    "Kj": "Shadow Daggers Knife | Damascus Steel",
    "Kn": "Shadow Daggers Knife | Fade",
    "Kw": "Shadow Daggers Knife | Forest DDPAT",
    "Kh": "Shadow Daggers Knife | Marble Fade",
    "Kr": "Shadow Daggers Knife | Night",
    "Kk": "Shadow Daggers Knife | Rust Coat",
    "Ky": "Shadow Daggers Knife | Safari Mesh",
    "Ku": "Shadow Daggers Knife | Scorched",
    "Kp": "Shadow Daggers Knife | Slaughter",
    "Kv": "Shadow Daggers Knife | Stained",
    "Km": "Shadow Daggers Knife | Tiger Tooth",
    "Kl": "Shadow Daggers Knife | Ultraviolet",
    "Kt": "Shadow Daggers Knife | Urban Masked",
#kukri
    "cc": "Kukri Knife | Blue Steel",
    "cb": "Kukri Knife | Case Hardened",
    "cZ": "Kukri Knife | Crimson Web",
    "cY": "Kukri Knife | Fade",
    "cd": "Kukri Knife | Night Stripe",
    "cf": "Kukri Knife | Forest DDPAT",
    "cg": "Kukri Knife | Scorched",
    "ch": "Kukri Knife | Boreal Forest",
    "cj": "Kukri Knife | Safari Mesh",
    "ca": "Kukri Knife | Slaughter",
    "ce": "Kukri Knife | Stained",
    "ci": "Kukri Knife | Urban Masked",
#gut
    "Im": "Gut Knife | Doppler",
    "U3": "Gut Knife | Doppler (Black Pearl)",
    "U4": "Gut Knife | Doppler (Phase 1)",
    "U5": "Gut Knife | Doppler (Phase 2)",
    "U6": "Gut Knife | Doppler (Phase 3)",
    "U7": "Gut Knife | Doppler (Phase 4)",
    "U8": "Gut Knife | Doppler (Ruby)",
    "U9": "Gut Knife | Doppler (Sapphire)",
    "Ih": "Gut Knife | Gamma Doppler",
    "Vm": "Gut Knife | Gamma Doppler (Emerald)",
    "Vn": "Gut Knife | Gamma Doppler (Phase 1)",
    "Vo": "Gut Knife | Gamma Doppler (Phase 2)",
    "Vp": "Gut Knife | Gamma Doppler (Phase 3)",
    "Vq": "Gut Knife | Gamma Doppler (Phase 4)",
    "Ii": "Gut Knife | Autotronic",
    "Ig": "Gut Knife | Black Laminate",
    "Ir": "Gut Knife | Blue Steel",
    "Is": "Gut Knife | Boreal Forest",
    "Ij": "Gut Knife | Bright Water",
    "It": "Gut Knife | Case Hardened",
    "Iu": "Gut Knife | Crimson Web",
    "Il": "Gut Knife | Damascus Steel",
    "Iv": "Gut Knife | Fade",
    "Iw": "Gut Knife | Forest DDPAT",
    "Ik": "Gut Knife | Freehand",
    "If": "Gut Knife | Lore",
    "In": "Gut Knife | Marble Fade",
    "Ix": "Gut Knife | Night",
    "Ip": "Gut Knife | Rust Coat",
    "Iy": "Gut Knife | Safari Mesh",
    "Iz": "Gut Knife | Scorched",
    "I0": "Gut Knife | Slaughter",
    "I1": "Gut Knife | Stained",
    "Io": "Gut Knife | Tiger Tooth",
    "Iq": "Gut Knife | Ultraviolet",
    "I2": "Gut Knife | Urban Masked",
#huntsman
    "Jt": "Huntsman Knife | Doppler",
    "WM": "Huntsman Knife | Doppler (Black Pearl)",
    "WN": "Huntsman Knife | Doppler (Phase 1)",
    "WO": "Huntsman Knife | Doppler (Phase 2)",
    "WP": "Huntsman Knife | Doppler (Phase 3)",
    "WQ": "Huntsman Knife | Doppler (Phase 4)",
    "WR": "Huntsman Knife | Doppler (Sapphire)",
    "WS": "Huntsman Knife | Doppler (Sapphire)",
    "Zd": "Huntsman Knife | Gamma Doppler",
    "Zf": "Huntsman Knife | Autotronic",
    "Zh": "Huntsman Knife | Black Laminate",
    "Zg": "Huntsman Knife | Bright Water",
    "Wo": "Huntsman Knife | Case Hardened (BlueGem)",
    "Wp": "Huntsman Knife | Case Hardened (Gold Gem)",
    "Zi": "Huntsman Knife | Freehand",
    "Ze": "Huntsman Knife | Lore",
    "J1": "Huntsman Knife | Blue Steel",
    "J4": "Huntsman Knife | Boreal Forest",
    "Jy": "Huntsman Knife | Case Hardened",
    "Jx": "Huntsman Knife | Crimson Web",
    "Jp": "Huntsman Knife | Damascus Steel",
    "Jv": "Huntsman Knife | Fade",
    "J5": "Huntsman Knife | Forest DDPAT",
    "Ju": "Huntsman Knife | Marble Fade",
    "Jz": "Huntsman Knife | Night",
    "Js": "Huntsman Knife | Rust Coat",
    "J3": "Huntsman Knife | Safari Mesh",
    "J2": "Huntsman Knife | Scorched",
    "Jw": "Huntsman Knife | Slaughter",
    "J0": "Huntsman Knife | Stained",
    "Jr": "Huntsman Knife | Tiger Tooth",
    "Jq": "Huntsman Knife | Ultraviolet",
    "J6": "Huntsman Knife | Urban Masked",
#bayo
    "H0": "Bayonet Knife | Doppler",
    "VH": "Bayonet Knife | Doppler (Black Pearl)",
    "VI": "Bayonet Knife | Doppler (Phase 1)",
    "VJ": "Bayonet Knife | Doppler (Phase 2)",
    "VK": "Bayonet Knife | Doppler (Phase 3)",
    "VL": "Bayonet Knife | Doppler (Phase 4)",
    "VM": "Bayonet Knife | Doppler (Ruby)",
    "VN": "Bayonet Knife | Doppler (Sapphire)",
    "Hv": "Bayonet Knife | Gamma Doppler",
    "Vc": "Bayonet Knife | Gamma Doppler (Emerald)",
    "Vd": "Bayonet Knife | Gamma Doppler (Phase 1)",
    "Ve": "Bayonet Knife | Gamma Doppler (Phase 2)",
    "Vf": "Bayonet Knife | Gamma Doppler (Phase 3)",
    "Vg": "Bayonet Knife | Gamma Doppler (Phase 4)",
    "Hw": "Bayonet Knife | Autotronic",
    "Hu": "Bayonet Knife | Black Laminate",
    "H5": "Bayonet Knife | Blue Steel",
    "H6": "Bayonet Knife | Boreal Forest",
    "Hx": "Bayonet Knife | Bright Water",
    "H7": "Bayonet Knife | Case Hardened",
    "H8": "Bayonet Knife | Crimson Web",
    "Hz": "Bayonet Knife | Damascus Steel",
    "H9": "Bayonet Knife | Fade",
    "IA": "Bayonet Knife | Forest DDRAT",
    "Hy": "Bayonet Knife | Freehand",
    "Ht": "Bayonet Knife | Lore",
    "H1": "Bayonet Knife | Marble Fade",
    "IB": "Bayonet Knife | Night",
    "H3": "Bayonet Knife | Rust Coat",
    "IC": "Bayonet Knife | Safari Mesh",
    "ID": "Bayonet Knife | Scorched",
    "IE": "Bayonet Knife | Slaughter",
    "IF": "Bayonet Knife | Stained",
    "H2": "Bayonet Knife | Tiger Tooth",
    "H4": "Bayonet Knife | Ultraviolet",
    "IG": "Bayonet Knife | Urban Masked",
#survival
    "fl": "Survival Knife | Doppler",
    "fi": "Survival Knife | Tiger Tooth",
    "fj": "Survival Knife | Rust Coat",
    "fk": "Survival Knife | Marble Fade",
    "fy": "Survival Knife | Ultraviolet",
    "fz": "Survival Knife | Damascus Steel",
    "P3": "Survival Knife | Blue Steel",
    "Pz": "Survival Knife | Boreal Forest",
    "Px": "Survival Knife | Case Hardened",
    "Py": "Survival Knife | Crimson Web",
    "Pv": "Survival Knife | Fade",
    "P4": "Survival Knife | Forest DDPAT",
    "P2": "Survival Knife | Night Stripe",
    "P5": "Survival Knife | Safari Mesh",
    "P1": "Survival Knife | Scorched",
    "Pw": "Survival Knife | Slaughter",
    "P0": "Survival Knife | Stained",
    "P6": "Survival Knife | Urban Masked",
#                                                                                                   GLOVES
#hand wraps
    "MT": "Hand Wraps | Arboreal",
    "LP": "Hand Wraps | Badlands",
    "MQ": "Hand Wraps | Cobalt Skulls",
    "MS": "Hand Wraps | Duct Tape",
    "LQ": "Hand Wraps | Leather",
    "MR": "Hand Wraps | Overprint",
    "LR": "Hand Wraps | Slaughter",
    "LS": "Hand Wraps | Spruce DDPAT",
    "UB": "Hand Wraps | CAUTION!",
    "UD": "Hand Wraps | Constrictor",
    "UE": "Hand Wraps | Desert Shamagh",
    "UC": "Hand Wraps | Giraffe",
#moto gloves
    "UI": "Moto Gloves | 3rd Commando Company",
    "UG": "Moto Gloves | Blood Pressure",
    "UF": "Moto Gloves | Finish Line",
    "UH": "Moto Gloves | Smoke Out",
    "LT": "Moto Gloves | Boom!",
    "LU": "Moto Gloves | Cool Mint",
    "LV": "Moto Gloves | Eclipse",
    "MX": "Moto Gloves | Polygon",
    "MU": "Moto Gloves | POW!",
    "LW": "Moto Gloves | Spearmint",
    "MW": "Moto Gloves | Transport",
    "MV": "Moto Gloves | Turtle",
#specialists glvs
    "UM": "Specialist Gloves | Field Agent",
    "UJ": "Specialist Gloves | Lt. Commander",
    "UK": "Specialist Gloves | Marble Fade",
    "UL": "Specialist Gloves | Tiger Strike",
    "ML": "Specialist Gloves | Buckshot",
    "LX": "Specialist Gloves | Crimson Kimono",
    "MJ": "Specialist Gloves | Crimson Web",
    "LY": "Specialist Gloves | Emerald Web",
    "MI": "Specialist Gloves | Fade",
    "LZ": "Specialist Gloves | Forest DDPAT",
    "La": "Specialist Gloves | Foundation",
    "MK": "Specialist Gloves | Mogul",
#sport gloves
    "MW": "Sport Gloves | Transport",
    "UO": "Sport Gloves | Big Game",
    "UQ": "Sport Gloves | Nocts",
    "UP": "Sport Gloves | Scarlet Shamagh",
    "UN": "Sport Gloves | Slingshot",
    "MO": "Sport Gloves | Amphibious",
    "Lb": "Sport Gloves | Arid",
    "MP": "Sport Gloves | Bronze Morph",
    "Lc": "Sport Gloves | Hedge Maze",
    "MM": "Sport Gloves | Omega",
    "Ld": "Sport Gloves | Pandora\"s Box",
    "Le": "Sport Gloves | Superconductor",
    "MN": "Sport Gloves | Vice",
#broken fang
    "T3": "Broken Fang Gloves | Jade",
    "T6": "Broken Fang Gloves | Needle Point",
    "T4": "Broken Fang Gloves | Unhinged",
    "T5": "Broken Fang Gloves | Yellow-banded",
#driver gloves
    "T9": "Driver Gloves | Black Tie",
    "UA": "Driver Gloves | Queen Jaguar",
    "T8": "Driver Gloves | Rezan the Red",
    "T7": "Driver Gloves | Snow Leopard",
    "LL": "Driver Gloves | Convoy",
    "LM": "Driver Gloves | Crimson Weave",
    "LN": "Driver Gloves | Diamondback",
    "MZ": "Driver Gloves | Imperial Plaid",
    "MY": "Driver Gloves | King Snake",
    "LO": "Driver Gloves | Lunar Weave",
    "Ma": "Driver Gloves | Overtake",
    "Mb": "Driver Gloves | Racing Green",
#bloodhound
    "LH": "Bloodhound Gloves | Bronzed",
    "LI": "Bloodhound Gloves | Charred",
    "LJ": "Bloodhound Gloves | Guerrilla",
    "LK": "Bloodhound Gloves | Snakebite",
#hydra
    "ME": "Hydra Gloves | Case Hardened",
    "MF": "Hydra Gloves | Emerald",
    "MH": "Hydra Gloves | Mangrove",
    "MG": "Hydra Gloves | Rattler",
#                                                                                                AGENTS
#master agents
    "Zx": "Master Agent | \"Medium Rare\" Crasswater",
    "YB": "Master Agent | \"The Doctor\" Romanov",
    "Zv": "Master Agent | Chef d\"Escadron Rouchard",
    "Zz": "Master Agent | Cmdr. Davida \"Goggles\" Fernandez",
    "Zy": "Master Agent | Cmdr. Frank \"Wet Sox\" Baroud",
    "X9": "Master Agent | Cmdr. Mae \"Dead Cold\" Jamison",
    "Z0": "Master Agent | Crasswater The Forgotten",
    "X7": "Master Agent | Lt. Commander Ricksaw",
    "X6": "Master Agent | Sir Bloody Darryl Royale",
    "X4": "Master Agent | Sir Bloody Loudmouth Darryl",
    "X3": "Master Agent | Sir Bloody Miami Darryl",
    "YA": "Master Agent | Sir Bloody Silent Darryl",
    "X8": "Master Agent | Sir Bloody Skullhead Darryl",
    "X5": "Master Agent | Special Agent Ava",
    "YC": "Master Agent | The Elite Mr. Muhlik",
    "Zw": "Master Agent | Vypa Sista of the Revolution",
#superior
    "YK": "Superior Agent | \"Two Times\" McCoy",
    "YI": "Superior Agent | \"Two Times\" McCoy",
    "YF": "Superior Agent | 1st Lieutenant Farlow",
    "Z5": "Superior Agent | Arno The Overgrown",
    "YG": "Superior Agent | Blackwolf",
    "Z3": "Superior Agent | Bloody Darryl The Strapped",
    "Z1": "Superior Agent | Chem-Haz Capitaine",
    "Z2": "Superior Agent | Elite Trapper Solman",
    "Z4": "Superior Agent | Lieutenant Rex Krikey",
    "YJ": "Superior Agent | Michael Syfers",
    "YD": "Superior Agent | Number K",
    "YM": "Superior Agent | Prof. Shahmat",
    "YH": "Superior Agent | Rezan The Ready",
    "YL": "Superior Agent | Rezan the Redshirt",
    "YE": "Superior Agent | Safecracker Voltzmann",
#exceptional agents
    "YR": "Exceptional Agent | \"Blueberries\" Buckshot",
    "YS": "Exceptional Agent | Buckshot",
    "Z6": "Exceptional Agent | Col. Mangos Dabisi",
    "YW": "Exceptional Agent | Dragomir | Sabre",
    "YN": "Exceptional Agent | Getaway Sally",
    "YQ": "Exceptional Agent | John \"Van Healen\" Kask",
    "Z9": "Exceptional Agent | Lieutenant \"Tree Hugger\" Farlow",
    "YO": "Exceptional Agent | Little Kev",
    "YT": "Exceptional Agent | Markus Delrow",
    "YV": "Exceptional Agent | Maximus",
    "Z7": "Exceptional Agent | Officer Jacques Beltram",
    "YX": "Exceptional Agent | Osiris",
    "YP": "Exceptional Agent | Sergeant Bombson",
    "YU": "Exceptional Agent | Slingshot",
    "aA": "Exceptional Agent | Sous-Lieutenant Medic Nationale",
    "Z8": "Exceptional Agent | Trapper",
#distinguisged
    "YZ": "Distinguished Agent | 3rd Commando Company",
    "aF": "Distinguished Agent | Aspirant",
    "Yd": "Distinguished Agent | B Squadron Officer",
    "Yb": "Distinguished Agent | Bio-Haz Specialist",
    "YY": "Distinguished Agent | Chem-Haz Specialist",
    "aC": "Distinguished Agent | D Squadron Officer",
    "Yf": "Distinguished Agent | Dragomir",
    "Yg": "Distinguished Agent | Enforcer",
    "Yi": "Distinguished Agent | Ground Rebel",
    "aE": "Distinguished Agent | Mr. Muhlik",
    "Ye": "Distinguished Agent | Operator",
    "aB": "Distinguished Agent | Primeiro Tenente",
    "Ya": "Distinguished Agent | Seal Team 6 Soldier",
    "Yh": "Distinguished Agent | Soldier",
    "Yc": "Distinguished Agent | Street Soldier",
    "aD": "Distinguished Agent | Trapper Aggressor",
#                                                                                           STICKERS
#holo
    "SK": "Sticker | Cheongsam (Holo)",
    "Sc": "Sticker | Distinguished Master Guardian (Holo)",
    "We": "Sticker | Killjoy (Holo)",
    "Sa": "Sticker | Legendary Eagle Master (Holo)",
    "Sb": "Sticker | Legendary Eagle (Holo)",
    "Se": "Sticker | Master Guardian (Holo)",
    "Sd": "Sticker | Master Guardian Elite (Holo)",
    "SY": "Sticker | Supreme Master First Class (Holo)",
    "X0": "Sticker | Fnatic (Holo) | Katowice 2014",
    "Xy": "Sticker | Natus Vincere (Holo) | Katowice 2014",
    "Xx": "Sticker | Virtus.Pro (Holo) | Katowice 2014",
    "X1": "Sticker | Titan (Holo) | Katowice 2014",
    "X2": "Sticker | Team Dignitas (Holo) | Katowice 2014",
    "Xz": "Sticker | iBUYPOWER (Holo) | Katowice 2014",
    "Yo": "Sticker | Nice Clutch (Holo)",
    "Yn": "Sticker | Cyber Romanov (Holo)",
    "Yr": "Sticker | Eye Contact (Holo)",
    "Yp": "Sticker | Handle With Care (Holo)",
    "Yq": "Sticker | I See You (Holo)",
    "Ym": "Sticker | Runtime (Holo)",
    "SZ": "Sticker | Gold Nova (Holo)",
    "RV": "Sticker | Baited (Holo)",
    "R7": "Sticker | Bash (Holo)",
    "Q4": "Sticker | Bish (Holo)",
    "RC": "Sticker | Boost (Holo)",
    "R8": "Sticker | Bosh (Holo)",
    "RY": "Sticker | Cluck (Holo)",
    "RF": "Sticker | Clutchman (Holo)",
    "RE": "Sticker | CS20 Classic (Holo)",
    "Rm": "Sticker | Devouring Flame (Holo)",
    "RD": "Sticker | Fire in the Hole (Holo)",
    "Q8": "Sticker | Firestarter (Holo)",
    "RW": "Sticker | First Blood (Holo)",
    "RZ": "Sticker | Free Hugs (Holo)",
    "Ro": "Sticker | Friendly Fire (Holo)",
    "RG": "Sticker | Guinea Pig (Holo)",
    "Q5": "Sticker | Incineration (Holo)",
    "bu": "Sticker | Infinite Diamond (Holo)",
    "Ry": "Sticker | Ivette (Holo)",
    "bj": "Sticker | Kawaii CT (Holo)",
    "bk": "Sticker | Kawaii T (Holo)",
    "R0": "Sticker | Kimberly (Holo)",
    "Qv": "Sticker | Lambda (Holo)",
    "R9": "Sticker | Let\"s Roll-oll (Holo)",
    "R2": "Sticker | Martha (Holo)",
    "R1": "Sticker | Merietta (Holo)",
    "RX": "Sticker | One Sting (Holo)",
    "bn": "Sticker | Pain Train (Holo)",
    "Rp": "Sticker | Retake Expert (Holo)",
    "RB": "Sticker | Rush 4x20 (Holo)",
    "Ra": "Sticker | Scavenger (Holo)",
    "Rz": "Sticker | Sherry (Holo)",
    "R3": "Sticker | Sherry (Holo)",
    "Rn": "Sticker | Small Arms (Holo)",
    "Q6": "Sticker | Tamara (Holo)",
    "bl": "Sticker | Cbbl (Holo)",
    "bm": "Sticker | Conspiracy Club (Holo)",
#foil
    "Yk": "Sticker | Ace Devil (Foil)",
    "Xf": "Sticker | Astralis (Foil) | Atlanta 2017",
    "W3": "Sticker | Astralis (Foil) | Berlin 2019",
    "TH": "Sticker | Astralis (Foil) | London 2018",
    "Yl": "Sticker | Bullet Hell (Foil)",
    "XR": "Sticker | cajunb (Foil) | Atlanta 2017",
    "TI": "Sticker | Cloud9 (Foil) | London 2018",
    "XJ": "Sticker | ELEAGUE (Foil) | Atlanta 2017",
    "XT": "Sticker | ESL (Foil) | Cologne 2015",
    "XC": "Sticker | FACEIT (Foil) | London 2018",
    "SJ": "Sticker | Fancy Koi (Foil)",
    "TJ": "Sticker | FaZe Clan (Foil) | London 2018",
    "XV": "Sticker | flusha (Foil) | Cologne 2015",
    "Xe": "Sticker | Fnatic (Foil) | Atlanta 2017",
    "XU": "Sticker | Fnatic (Foil) | Cologne 2015",
    "TK": "Sticker | Fnatic (Foil) | London 2018",
    "XN": "Sticker | G2 Esports (Foil) | Atlanta 2017",
    "TL": "Sticker | G2 Esports (Foil) | London 2018",
    "aZ": "Sticker | G2 Esports (Foil) | Stockholm 2021",
    "Xc": "Sticker | GuardiaN (Foil) | Cologne 2015",
    "XW": "Sticker | JW (Foil) | Cologne 2015",
    "XS": "Sticker | k0nfig (Foil) | Atlanta 2017",
    "XY": "Sticker | kennyS (Foil) | Cologne 2015",
    "TQ": "Sticker | MIBR (Foil) | London 2018",
    "TM": "Sticker | mousesports (Foil) | London 2018",
    "Wa": "Sticker | Move It (Foil)",
    "Xa": "Sticker | Natus Vincere (Foil) | Cologne 2015",
    "TN": "Sticker | Natus Vincere (Foil) | London 2018",
    "aY": "Sticker | Natus Vincere (Foil) | Stockholm 2021",
    "XZ": "Sticker | NBK- (Foil) | Cologne 2015",
    "XQ": "Sticker | North (Foil) | Atlanta 2017",
    "W6": "Sticker | NRG (Foil) | Berlin 2019",
    "XM": "Sticker | pashaBiceps (Foil) | Atlanta 2017",
    "Yj": "Sticker | Purrurists (Foil)",
    "XP": "Sticker | ScreaM (Foil) | Atlanta 2017",
    "XO": "Sticker | shox (Foil) | Atlanta 2017",
    "SX": "Sticker | Silver (Foil)",
    "XL": "Sticker | Snax (Foil) | Atlanta 2017",
    "W2": "Sticker | StarLadder (Foil) | Berlin 2019",
    "XX": "Sticker | Team EnVyUs (Foil) | Cologne 2015",
    "Xd": "Sticker | Team Liquid (Foil) | Atlanta 2017",
    "W9": "Sticker | Team Liquid (Foil) | Berlin 2019",
    "TP": "Sticker | Team Liquid (Foil) | London 2018",
    "XK": "Sticker | Virtus.Pro (Foil) | Atlanta 2017",
    "TO": "Sticker | Winstrike Team (Foil) | London 2018",
    "Xb": "Sticker | Zeus (Foil) | Cologne 2015",
    "Q9": "Sticker | All Hail The King (Foil)",
    "RU": "Sticker | Bite Me (Foil)",
    "Rk": "Sticker | Bullet Rain (Foil)",
    "Rl": "Sticker | Camper (Foil)",
    "Hp": "Sticker | Crown (Foil)",
    "RA": "Sticker | Door Stuck (Foil)",
    "Qz": "Sticker | Dragon Lore (Foil)",
    "Q0": "Sticker | Flammable (Foil)",
    "Q1": "Sticker | Global Elite (Foil)",
    "Q2": "Sticker | Gold Web (Foil)",
    "bh": "Sticker | In The Fire (Foil)",
    "RT": "Sticker | Lurker (Foil)",
    "Q3": "Sticker | New Sheriff (Foil)",
    "Hs": "Sticker | Stupid Banana (Foil)",
    "Hr": "Sticker | Swag (Foil)",
    "Hq": "Sticker | The Pro (Foil)",
    "RS": "Sticker | Toxic (Foil)",
    "bg": "Sticker | Showdown (Foil)",
    "SI": "Sticker | Guardian Dragon (Foil)",
#gold
    "W4": "Sticker | device (Gold) | Berlin 2019",
    "XD": "Sticker | dupreeh (Gold) | London 2018",
    "aU": "Sticker | electroNic (Gold) | Stockholm 2021",
    "XB": "Sticker | EliGE (Gold) | Berlin 2019",
    "XG": "Sticker | flamie (Gold) | London 2018",
    "aX": "Sticker | G2 Esports (Gold) | Stockholm 2021",
    "XE": "Sticker | gla1ve (Gold) | London 2018",
    "XI": "Sticker | GuardiaN (Gold) | London 2018",
    "aV": "Sticker | huNter- (Gold) | Stockholm 2021",
    "aW": "Sticker | Natus Vincere (Gold) | Stockholm 2021",
    "aS": "Sticker | NiKo (Gold) | Stockholm 2021",
    "XH": "Sticker | olofmeister (Gold) | London 2018",
    "XF": "Sticker | s1mple (Gold) | London 2018",
    "aT": "Sticker | s1mple (Gold) | Stockholm 2021",
    "W8": "Sticker | stanislaw (Gold) | Berlin 2019",
    "XA": "Sticker | Stewie2K (Gold) | Berlin 2019",
    "W7": "Sticker | tarik (Gold) | Berlin 2019",
    "W5": "Sticker | Xyp9x (Gold) | Berlin 2019",
#regular
    "SM": "Sticker | Cheongsam",
    "SH": "Sticker | Chicken Lover",
    "Yw": "Sticker | Clutch Or Kick",
    "TR": "Sticker | Dirty Money",
    "Sl": "Sticker | Distinguished Master Guardian",
    "Yz": "Sticker | Dr. Dazzles",
    "TS": "Sticker | Drug War Veteran",
    "Ys": "Sticker | EZ",
    "SQ": "Sticker | Fancy Koi",
    "Yu": "Sticker | Fast Banana",
    "TT": "Sticker | Fnatic | Katowice 2014",
    "Sz": "Sticker | Global Elite",
    "Sf": "Sticker | Gold Nova",
    "Wb": "Sticker | Hamster Hawk",
    "Y1": "Sticker | Hard Carry",
    "TU": "Sticker | HellRaisers | Katowice 2014",
    "SW": "Sticker | Hotpot",
    "TW": "Sticker | iBUYPOWER | Katowice 2014",
    "TX": "Sticker | Killjoy",
    "Y0": "Sticker | Kitted Out",
    "Sg": "Sticker | Legendary Eagle",
    "Sm": "Sticker | Legendary Eagle Master",
    "SG": "Sticker | Let\"s Roll-oll",
    "TY": "Sticker | LGB eSports | Katowice 2014",
    "TZ": "Sticker | Luck Skill",
    "Ta": "Sticker | Lucky 13",
    "SO": "Sticker | Mahjong Fa",
    "SR": "Sticker | Mahjong Rooster",
    "SN": "Sticker | Mahjong Zhong",
    "Wc": "Sticker | Massive Pear",
    "Sk": "Sticker | Master Guardian",
    "Si": "Sticker | Master Guardian Elite",
    "SF": "Sticker | Metal",
    "Tb": "Sticker | Mister Chief",
    "Y3": "Sticker | Nademan",
    "Tc": "Sticker | Natus Vincere | Katowice 2014",
    "Td": "Sticker | Ninjas in Pyjamas | Katowice 2014",
    "Yv": "Sticker | No Time",
    "SS": "Sticker | Noodles",
    "Y2": "Sticker | Retro Leet",
    "SU": "Sticker | Rice Bomb",
    "Sh": "Sticker | Silver",
    "Yx": "Sticker | Speedy T",
    "Te": "Sticker | Stay Frosty",
    "Sj": "Sticker | Supreme Master First Class",
    "Sy": "Sticker | Tamara",
    "Tf": "Sticker | Team Dignitas | Katowice 2014",
    "SV": "Sticker | Terror Rice",
    "Yt": "Sticker | This Is Fine (CT)",
    "Tg": "Sticker | Titan | Katowice 2014",
    "ST": "Sticker | Toy Tiger",
    "Th": "Sticker | Trick Or Threat",
    "Ti": "Sticker | Virtus.Pro | Katowice 2014",
    "Yy": "Sticker | War",
    "SL": "Sticker | Water Gun",
    "Tj": "Sticker | Witch",
    "Lw": "Sticker | Awp Country",
    "RL": "Sticker | Aztec",
    "bv": "Sticker | B Hop",
    "br": "Sticker | Baby Cerberus",
    "bs": "Sticker | Baby Fire Serpent",
    "bo": "Sticker | Baby Howl",
    "bq": "Sticker | Baby Lore",
    "bp": "Sticker | Baby Medusa",
    "Rf": "Sticker | Baited",
    "SC": "Sticker | Banana",
    "Rg": "Sticker | Bite Me",
    "bi": "Sticker | Blue Gem (Glitter)",
    "Hh": "Sticker | Bomb Code",
    "Qw": "Sticker | Bomb Doge",
    "Rs": "Sticker | Bullet Rain",
    "Ru": "Sticker | Camper",
    "Re": "Sticker | Cluck",
    "Rw": "Sticker | Dessert Eagle",
    "Rt": "Sticker | Devouring Flame",
    "bf": "Sticker | DJ Safecracker (Lenticular)",
    "Hb": "Sticker | Easy Peasy",
    "Hi": "Sticker | Eco Rust",
    "Rv": "Sticker | Entry Fragger",
    "Rb": "Sticker | First Blood",
    "Hg": "Sticker | Flickshot",
    "Rj": "Sticker | Free Hugs",
    "RK": "Sticker | Friend Code",
    "Rr": "Sticker | Friendly Fire",
    "Hd": "Sticker | Good Game",
    "SD": "Sticker | Good Luck",
    "SE": "Sticker | Have Fun",
    "TV": "Sticker | Ho Ho Ho",
    "Mc": "Sticker | Howling Dawn",
    "R5": "Sticker | Ivette",
    "R4": "Sticker | Kimberly",
    "Hm": "Sticker | Merietta",
    "RR": "Sticker | Mondays",
    "SB": "Sticker | Nice Shot",
    "Ho": "Sticker | Ninja Defuse",
    "RI": "Sticker | Nuke Beast",
    "RP": "Sticker | Obey SAS",
    "Ri": "Sticker | One Sting",
    "Hc": "Sticker | Pigeon Master",
    "RM": "Sticker | Pixel Avenger",
    "Hf": "Sticker | Pros Don\"t Fake",
    "Rx": "Sticker | Retake Expert",
    "Qx": "Sticker | SAS Chicken",
    "Rh": "Sticker | Scavenger",
    "RN": "Sticker | Separate Pixels",
    "Rq": "Sticker | Small Arms",
    "RJ": "Sticker | Surf\"s Up",
    "Hj": "Sticker | Terrorized",
    "Hl": "Sticker | The Awper",
    "Hk": "Sticker | The Fragger",
    "He": "Sticker | Thug Life",
    "RO": "Sticker | Too Late",
    "RH": "Sticker | Too Old for This",
    "Rd": "Sticker | Toxic",
    "be": "Sticker | TV Installation (Lenticular)",
    "SA": "Sticker | Welcome to The Clutch",
    "Qy": "Sticker | Winged Defuser",
}

# -----------------------
# Streamlit Page Setup
# -----------------------
st.set_page_config(
    page_title="Advanced Item Filter",
    page_icon="🔍",
    layout="wide",
    initial_sidebar_state="expanded"
)

st.markdown(
    """
    <style>
    body {
        background-color: #1e1e1e;
        color: #e6e6e6;
    }
    .stButton>button {
        background-color: #2d2d2d;
        color: white;
    }
    .stButton>button:hover {
        background-color: #3a3a3a;
    }
    .stTextInput>div>div>input {
        background-color: #252526;
        color: white;
        border: none;
    }
    </style>
    """,
    unsafe_allow_html=True
)

# -----------------------
# Sidebar - Qualities & Info
# -----------------------
st.sidebar.header("Item Qualities / Notes")
st.sidebar.markdown("""
**QUALITY CODES**
- ST SV: 
46|FN _ 36|MW _ 26|FT _ 16|WW _ 06|BS
- ST: 
44|FN _ 34|MW _ 24|FT _ 14|WW _ 04|BS
- SV: 
42|FN _ 32|MW _ 22|FT _ 12|WW _ 02|BS
- NOTHING 
40|FN _ 30|MW _ 20|FT _ 10|WW _ 00|BS
""")

# -----------------------
# Main Interface
# -----------------------
st.title("Advanced Item Filter")

# Search input
query = st.text_input("Search by ID, Weapon, or Skin").lower()

# Sorting selectbox
sort_option = st.selectbox("Sort", ["A–Z", "Z–A"])

# Filter items
filtered_items = [
    (item_id, name)
    for item_id, name in ITEMS.items()
    if query in f"{item_id} {name}".lower()
]

# Sort items
filtered_items.sort(key=lambda x: x[1].lower(), reverse=(sort_option=="Z–A"))

# Display results
if filtered_items:
    for item_id, name in filtered_items:
        st.markdown(f"**{item_id}** → {name}")
else:
    st.info("No items match your search.")

# Copy to clipboard using st.text_area
st.text_area("Copy All Visible IDs", value="\n".join([i for i, _ in filtered_items]), height=100)

# Signature at bottom
st.markdown("<p style='text-align:right;color:#9a9a9a;'>by Marco🥒</p>", unsafe_allow_html=True)
